### ISSUE TITLE
[BUG REPORT] Direct Shear Test

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2068] opened 2024-09-18 08:41 UTC
### **Bug Reported on 18 September, 14:11 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Direct Shear Test
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation not working 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/direct-shear-test/simulation.html
Email - kajalsaini5668901@gmail.com

**Comment by shraddha** [comment] 2024-11-28 10:01
This bug is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2332 Hence closing it.

**Closed by shraddha** 2024-11-28 10:01 UTC
Labels: duplicate, IIITH
