### ISSUE TITLE
[BUG REPORT] Advanced Control Flow

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#480] opened 2024-07-18 10:00 UTC
### **Bug Reported on 18 July, 15:30 GMT +5:50 in** 
Lab - Computer programming
Experiment - Advanced Control Flow
**Type(s) of Issue -**
* Content Not Visible

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/advanced-control-flow/posttest.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1721296806544.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-21 13:31
This bug is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/476 hence closing it.

**Closed by shraddha** 2024-11-21 13:31 UTC
Labels: duplicate, IIITH
