### ISSUE TITLE
[BUG REPORT] Reynold's Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4676] opened 2024-12-10 07:57 UTC
### **Bug Reported on 10 December, 13:27 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Reynold's Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation is not working 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/reynolds/simulation.html
Email - s22_sawale_ganesh@mgmcen.ac.in

**Comment by shraddha** [comment] 2024-12-11 08:47
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2542 Hence closing.

**Closed by shraddha** 2024-12-11 08:47 UTC
Labels: duplicate, IIITH
