### ISSUE TITLE
[BUG REPORT] Virtual Labs Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1468] opened 2024-08-27 06:02 UTC
### **Bug Reported on 27 August, 11:32 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Simulation Not Working

Additional info- cant input the start range in analysis of prime numbers

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html

**Comment by vlabiitk** [comment] 2024-12-26 10:14
Duplicate of #4176

**Closed by vlabiitk** 2024-12-26 10:14 UTC
Labels: duplicate, IITK
