### ISSUE TITLE
[BUG REPORT] Virtual Labs Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#723] opened 2024-07-29 05:22 UTC
### **Bug Reported on 29 July, 10:52 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**
* Incorrect Content
* Content Not Visible
* Page Not Loading
* Insufficient/Incorrect Instructions
* Incorrect Results/Observations
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/simulation.html

**Comment by shraddha** [comment] 2024-11-28 11:48
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1052 Hence closing it.

**Closed by shraddha** 2024-11-28 11:48 UTC
Labels: duplicate, IIITH
