### ISSUE TITLE
[BUG REPORT] Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4876] opened 2024-12-20 11:43 UTC
### **Bug Reported on 20 December, 17:13 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Not working 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 06:43
Duplicate of #1709

**Closed by vlabiitk** 2024-12-24 06:43 UTC
Labels: duplicate, IITK
