### ISSUE TITLE
[BUG REPORT] Virtual Labs Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2368] opened 2024-09-25 05:10 UTC
### **Bug Reported on 25 September, 10:40 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Simulation Not Working

Additional info- simulation not loading only a blank page is appearing.

UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html
Email - mauryasudeep218@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1727241048394.png" alt="Issue image">

**Comment by vlab-iitr** [comment] 2024-12-09 05:33
Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 05:33 UTC
Labels: duplicate, IITR
