### ISSUE TITLE
[BUG REPORT] Virtual Labs Representation of Integers and their Arithmetic

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1111] opened 2024-08-14 04:39 UTC
### **Bug Reported on 14 August, 10:9 GMT +5:50 in** 
Lab - Computer Organisation
Experiment - Representation of Integers and their Arithmetic
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- 2's compliment after row #12 are wrong. Hence, answers ,after taking a number from row#12 onwards , are wrong

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse11-iiith.vlabs.ac.in/exp/integers-arithmetic/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1723610385474.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 07:04
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1053 Hence closing it.

**Closed by shraddha** 2024-11-28 07:04 UTC
Labels: duplicate, IIITH
