### ISSUE TITLE
[BUG REPORT] Virtual Labs Familiarization with the fluorescence Instrumentation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4033] opened 2024-11-09 18:45 UTC
### **Bug Reported on 9 November, 19:45 GMT +1:0 in** 
Lab - Molecular Fluorescence Spectroscopy
Experiment - Familiarization with the fluorescence Instrumentation
**Type(s) of Issue -**
* Simulation Not Working
* Simulation Not Working

Additional info- Step10 of Principle of Absorption, Florescence and Phosphorescence does not work

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
Experiment Link - https://mfs-iiith.vlabs.ac.in/exp/fluorescence-instrumentation/simulation.html

**Comment by shraddha** [comment] 2024-11-28 11:33
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1666 Hence closing.

**Closed by shraddha** 2024-11-28 11:33 UTC
Labels: duplicate, IIITH
