### ISSUE TITLE
[BUG REPORT] Orifices Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4616] opened 2024-12-07 08:06 UTC
### **Bug Reported on 7 December, 13:36 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Orifices Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Not forwarded next step 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/orifices/simulation.html

**Comment by shraddha** [comment] 2024-12-09 04:51
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/289 and hence closing.

**Closed by shraddha** 2024-12-09 04:51 UTC
Labels: duplicate, IIITH
