### ISSUE TITLE
[BUG REPORT] Determination of TS,TDS and TSS in water

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#985] opened 2024-08-08 05:21 UTC
### **Bug Reported on 8 August, 10:51 GMT +5:50 in** 
Lab - Environmental Engineering 1
Experiment - Determination of TS,TDS and TSS in water
**Type(s) of Issue -**
* Page Not Loading

Additional info- 🙄

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://ee1-nitk.vlabs.ac.in/exp/determination-of-ts/

**Comment by SOLVE-NITK** [comment] 2024-12-03 07:23
The page is loading. The issue is not relevant to the experiment. Closing the issue with the label 'Inappropriate

**Closed by SOLVE-NITK** 2024-12-03 07:23 UTC
Labels: NITK, Inappropriate
