### ISSUE TITLE
[BUG REPORT] Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2269] opened 2024-09-23 09:09 UTC
### **Bug Reported on 23 September, 14:39 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Page Not Loading

Additional info- Not loading fast. 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/assignment.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1727081814283.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-21 11:36
This bug is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/409 hence closing it

**Closed by shraddha** 2024-11-21 11:36 UTC
Labels: duplicate, IIITH
