### ISSUE TITLE
[BUG REPORT] Virtual Labs Quick Sort

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2240] opened 2024-09-23 05:51 UTC
### **Bug Reported on 23 September, 11:21 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Quick Sort
**Type(s) of Issue -**

Additional info- the icons  which is on left side of RATE ME button is not working and the image is not prsent

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/quick-sort/quick-sort/quicksort-exercise.html

**Comment by shraddha** [comment] 2024-11-23 04:28
This bug is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4261, hence closing it.

**Closed by shraddha** 2024-11-23 04:28 UTC
Labels: duplicate, IIITH
