### ISSUE TITLE
[BUG REPORT] Polynomial Arithmetic using linked lists

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4460] opened 2024-11-28 19:02 UTC
### **Bug Reported on 29 November, 0:32 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Polynomial Arithmetic using linked lists
**Type(s) of Issue -**
* Content Not Visible

Additional info- .

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/poly-arithmetic/index.html

**Comment by shraddha** [comment] 2024-11-29 09:52
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3368 Hence closing it.

**Closed by shraddha** 2024-11-29 09:52 UTC
Labels: duplicate, IIITH
