### ISSUE TITLE
[BUG REPORT] Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2274] opened 2024-09-23 09:14 UTC
### **Bug Reported on 23 September, 14:44 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- Vgg

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/assignment.html

**Comment by shraddha** [comment] 2024-11-21 11:31
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/409 Hence closing it.

**Closed by shraddha** 2024-11-21 11:31 UTC
Labels: duplicate, IIITH
