### ISSUE TITLE
[BUG REPORT] Virtual Labs Schematic Design Of Transistor Level Inverter

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#434] opened 2024-07-16 07:47 UTC
### **Bug Reported on 16 July, 13:17 GMT +5:50 in** 
Lab - VLSI
Experiment - Schematic Design Of Transistor Level Inverter
**Type(s) of Issue -**
* Content Not Visible

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://cse14-iiith.vlabs.ac.in/exp/transistor-level-inverter/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1721116057134.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 14:08
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/298 Hence closing.

**Closed by shraddha** 2024-11-28 14:08 UTC
Labels: duplicate, IIITH
