### ISSUE TITLE
[BUG REPORT] Virtual Labs Forming Sentences-1

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#370] opened 2024-07-05 03:52 UTC
### **Bug Reported on 5 July, 9:22 GMT +5:50 in** 
Lab - Computational Linguistics
Experiment - Forming Sentences-1
**Type(s) of Issue -**
* Simulation Not Working

Additional info- After select the language it shows garbage data i.e error

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://cl-iiith.vlabs.ac.in/exp/forming-sentences-1/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1720151572521.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-29 11:14
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3771 Hence closing.

**Closed by shraddha** 2024-11-29 11:14 UTC
Labels: duplicate, IIITH
