### ISSUE TITLE
[BUG REPORT] Virtual Labs Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#361] opened 2024-07-04 04:17 UTC
### **Bug Reported on 4 July, 14:17 GMT +10:0 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Content Not Visible

Additional info- Content isn't visible

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html
Email - madhushri1801@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1720066668597.png" alt="Issue image">

**Comment by vlab-iitr** [comment] 2024-12-09 05:20
Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 05:20 UTC
Labels: IITR
