### ISSUE TITLE
[BUG REPORT] Virtual Labs Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4055] opened 2024-11-11 08:14 UTC
### **Bug Reported on 11 November, 13:44 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Simulation Not Working
* Content Not Visible

Additional info- the part 5 is not showing the result no output 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html

**Comment by shraddha** [comment] 2024-11-19 15:24
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 15:24 UTC
Labels: duplicate, IIITH
