### ISSUE TITLE
[BUG REPORT] Impact of jet

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2945] opened 2024-10-07 07:42 UTC
### **Bug Reported on 7 October, 13:12 GMT +5:50 in** 
Lab - Fluid Mechanics
Experiment - Impact of jet
**Type(s) of Issue -**
* Insufficient Content

Additional info- Mmmmmm

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36
Experiment Link - https://fm-nitk.vlabs.ac.in/exp/impact-of-jet/theory.html

**Comment by SOLVE-NITK** [comment] 2024-11-27 06:02
This issue has been marked as inappropriate and closed due to unclear and insufficient information.

**Comment by shraddha** [comment] 2024-12-05 14:29
Please review the labeling by referring to the section 'Categorize the bug' from [Bug Management Process](https://vlead.vlabs.ac.in/development/#bug-processing-guide). This bug seems to fall into either of these categories - invalid or Not Reproducible. Hence removing the inappropriate label and reopening the bug for reassignment of right label.

**Comment by SOLVE-NITK** [comment] 2024-12-17 06:52
Additional info is inappropriate/not relevant. Changed the label to "invalid". 
@shraddha

**Closed by SOLVE-NITK** 2024-12-17 06:52 UTC
Labels: invalid, NITK
