### ISSUE TITLE
[BUG REPORT] Virtual Labs Digital Signatures

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2290] opened 2024-09-23 11:03 UTC
### **Bug Reported on 23 September, 11:3 GMT -7:0 in** 
Lab - Cryptography
Experiment - Digital Signatures
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- chal nahi raha ek jagah pe khada hai 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/digital-signatures/simulation.html

**Comment by shraddha** [comment] 2024-11-28 14:55
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/248 Hence closing.

**Closed by shraddha** 2024-11-28 14:55 UTC
Labels: duplicate, IIITH
