### ISSUE TITLE
[BUG REPORT] To study the Load Characteristics of DC shunt generator

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3229] opened 2024-10-15 06:56 UTC
### **Bug Reported on 15 October, 12:26 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - To study the Load Characteristics of DC shunt generator
**Type(s) of Issue -**
* Page Not Loading
* Simulation Not Working

Additional info- The connecting ports are not visible

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/load-characteristics-dc-shunt/simulation.html

**Comment by vlab-iitr** [comment] 2024-12-09 10:54
Closing it, as it is a duplicate of #3021

**Closed by vlab-iitr** 2024-12-09 10:54 UTC
Labels: duplicate, IITR
