### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#976] opened 2024-08-07 18:18 UTC
### **Bug Reported on 7 August, 23:48 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Multiplication not working 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/simulation.html
Email - koliprajwal108@gmail.com

**Comment by vlabiitk** [comment] 2024-12-24 09:49
Duplicate of #1303

**Closed by vlabiitk** 2024-12-24 09:49 UTC
Labels: duplicate, IITK
