### ISSUE TITLE
[BUG REPORT] Venturi Meter Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#850] opened 2024-08-03 03:46 UTC
### **Bug Reported on 3 August, 9:16 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Venturi Meter Experiment
**Type(s) of Issue -**

Additional info- It is not working properly 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/venturi-meter/simulation.html

**Comment by shraddha** [comment] 2024-11-28 14:11
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/426 Hence closing.

**Closed by shraddha** 2024-11-28 14:11 UTC
Labels: duplicate, IIITH
