### ISSUE TITLE
[BUG REPORT] Virtual Labs Strings

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3239] opened 2024-10-15 08:29 UTC
### **Bug Reported on 15 October, 13:59 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Strings
**Type(s) of Issue -**
* Content Not Visible
* Simulation Not Working
* Incorrect Results/Observations
* Page Not Loading

Additional info- bn vb

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/strings/simulation.html

**Comment by vlabiitk** [comment] 2024-12-20 12:26
This issue is duplicate of #3245.

**Closed by vlabiitk** 2024-12-20 12:26 UTC
Labels: duplicate, IITK
