### ISSUE TITLE
[BUG REPORT] Virtual Labs Pointers

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2470] opened 2024-09-27 03:24 UTC
### **Bug Reported on 27 September, 8:54 GMT +5:50 in** 
Lab - Computer programming
Experiment - Pointers
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- idk why

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/pointers/simulation.html

**Comment by shraddha** [comment] 2024-11-28 04:22
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/306 hence closing.

**Closed by shraddha** 2024-11-28 04:22 UTC
Labels: duplicate, IIITH
