### ISSUE TITLE
[BUG REPORT] Virtual Labs Cryptographic Hash Functions and Applications

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1432] opened 2024-08-26 06:24 UTC
### **Bug Reported on 26 August, 11:54 GMT +5:50 in** 
Lab - Cryptography
Experiment - Cryptographic Hash Functions and Applications
**Type(s) of Issue -**

Additional info- NOT PROPER INSTRUCTIONS IN THE PROCURE

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/hash-functions/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1724653264951.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 05:08
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1108 hence closing it.

**Closed by shraddha** 2024-11-28 05:08 UTC
Labels: duplicate, IIITH
