### ISSUE TITLE
[BUG REPORT] Permeability

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2321] opened 2024-09-24 06:50 UTC
### **Bug Reported on 23 September, 20:24 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Permeability
**Type(s) of Issue -**
* Content Not Visible
* Page Not Loading
* Incorrect Options
* Incorrect Answer
* Incorrect Question
* Incorrect Content

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/permeability/posttest.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1727160612429.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 15:09
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2322 Hence closing.

**Closed by shraddha** 2024-11-28 15:09 UTC
Labels: duplicate, IIITH
