### ISSUE TITLE
[BUG REPORT] Virtual Labs Linked lists

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4297] opened 2024-11-20 10:28 UTC
### **Bug Reported on 20 November, 15:57 GMT +10:0 in** 
Lab - Data Structures - 1
Experiment - Linked lists
**Type(s) of Issue -**
* Insufficient/Incorrect Instructions

Additional info- 8 VALUES ARE GIVEN BUT IT CAN ONLY ABBLE TO TAKE 7 NODES

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/linked-list/circular-linked-list/cllexercise.html

**Comment by priya100raman** [comment] 2024-11-21 08:57
Duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4298

**Closed by priya100raman** 2024-11-21 08:57 UTC
Labels: duplicate, IIITH
