### ISSUE TITLE
[BUG REPORT] Water Content

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2466] opened 2024-09-26 18:38 UTC
### **Bug Reported on 26 September, 21:37 GMT +3:0 in** 
Lab - Soil Mechanics
Experiment - Water Content
**Type(s) of Issue -**
* Simulation Not Working

Additional info-  Simulation of experiment

UserAgent: Mozilla/5.0 (Linux; Android 10; FRL-L22; HMSCore 6.14.0.301) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.196 HuaweiBrowser/15.0.4.312 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/water-content/simulation.html
Email - alaa3wad2023@gmail.com

**Comment by shraddha** [comment] 2024-11-28 14:58
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1043 Hence closing.

**Closed by shraddha** 2024-11-28 14:58 UTC
Labels: duplicate, IIITH
