### ISSUE TITLE
[BUG REPORT] Solvent Effects on the UV-visible Absorption Spectra

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4583] opened 2024-12-04 12:55 UTC
### **Bug Reported on 4 December, 18:25 GMT +5:50 in** 
Lab - Molecular Absorption Spectroscopy
Experiment - Solvent Effects on the UV-visible Absorption Spectra
**Type(s) of Issue -**
* Incorrect Content

Additional info- U-v visible 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://mas-iiith.vlabs.ac.in/exp/uv-visible-spectra/
Email - yogisri.0654@gmail.com

**Comment by shraddha** [comment] 2024-12-05 11:18
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4567 Hence closing.

**Closed by shraddha** 2024-12-05 11:18 UTC
Labels: duplicate, IIITH

**Comment by shraddha** [comment] 2025-03-13 10:38
This bug was wrongly associated with an issue with other experiment, hence correcting it and marking it as a bug.
