### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Mono-alphabetic Substitution Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#421] opened 2024-07-15 09:40 UTC
### **Bug Reported on 15 July, 15:10 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Mono-alphabetic Substitution Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations
* Content Not Visible
* Insufficient/Incorrect Instructions

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/substitution-cipher/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1721036428211.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 07:24
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/411 Hence closing.

**Closed by shraddha** 2024-11-28 07:24 UTC
Labels: duplicate, IIITH
