### ISSUE TITLE
[BUG REPORT] Virtual Labs Familiarization with the fluorescence Instrumentation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2784] opened 2024-10-05 06:37 UTC
### **Bug Reported on 5 October, 12:7 GMT +5:50 in** 
Lab - Molecular Fluorescence Spectroscopy
Experiment - Familiarization with the fluorescence Instrumentation
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://mfs-iiith.vlabs.ac.in/exp/fluorescence-instrumentation/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1728110238596.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 11:32
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1666 Hence closing.

**Closed by shraddha** 2024-11-28 11:32 UTC
Labels: duplicate, IIITH
