### ISSUE TITLE
[BUG REPORT] Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4335] opened 2024-11-22 08:30 UTC
### **Bug Reported on 22 November, 14:0 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Field resistance coil is not working in Android phone 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html
Email - abhishek480raghav@gmail.com

**Comment by vlab-iitr** [comment] 2024-12-09 06:22
Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 06:22 UTC
Labels: duplicate, IITR
