### ISSUE TITLE
[BUG REPORT] Arrays

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4854] opened 2024-12-19 03:45 UTC
### **Bug Reported on 19 December, 9:15 GMT +5:50 in** 
Lab - Computer programming
Experiment - Arrays
**Type(s) of Issue -**
* Incorrect Content

Additional info- Xyz

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/arrays/simulation.html

**Comment by shraddha** [comment] 2024-12-25 05:58
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1469 Hence closing.

**Closed by shraddha** 2024-12-25 05:58 UTC
Labels: duplicate, IIITH
