### ISSUE TITLE
[BUG REPORT] Dynamics analysis of slider crank mechanism

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1442] opened 2024-08-26 10:30 UTC
### **Bug Reported on 26 August, 16:0 GMT +5:50 in** 
Lab - Dynamics of Machine
Experiment - Dynamics analysis of slider crank mechanism
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- No

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://dom-nitk.vlabs.ac.in/exp/slider-crank-mechanism/simulation.html
Email - ingleritesh76@gmail.com

**Comment by SOLVE-NITK** [comment] 2024-12-05 11:39
Unable to reproduce. Additional details are required to analyze further

**Comment by shraddha** [comment] 2024-12-05 14:34
Please review the labeling by referring to the section 'Categorize the bug' from [Bug Management Process](https://vlead.vlabs.ac.in/development/#bug-processing-guide). This bug seems to fall into Not Reproducible category. Hence removing the inappropriate label and reopening the bug for reassignment of right label.

**Comment by SOLVE-NITK** [comment] 2024-12-17 07:50
Simulation is working as expected, hence marking it as Not Reproducible and closing it.

**Closed by SOLVE-NITK** 2024-12-17 07:50 UTC
Labels: NITK, Not Reproducible
