### ISSUE TITLE
[BUG REPORT] Virtual Labs Representation of Integers and their Arithmetic

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1110] opened 2024-08-14 04:36 UTC
### **Bug Reported on 14 August, 10:6 GMT +5:50 in** 
Lab - Computer Organisation
Experiment - Representation of Integers and their Arithmetic
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- 2's compliment after row 13 are repeated and hence, are wrong.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse11-iiith.vlabs.ac.in/exp/integers-arithmetic/simulation.html

**Comment by shraddha** [comment] 2024-11-28 07:03
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1053 hence closing it.

**Closed by shraddha** 2024-11-28 07:03 UTC
Labels: duplicate, IIITH
