### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#576] opened 2024-07-23 04:55 UTC
### **Bug Reported on 23 July, 10:25 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Simulation Not Working

Additional info- your simulation is not working 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/assignment.html

**Comment by shraddha** [comment] 2024-11-21 11:18
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/371 hence closing it.

**Closed by shraddha** 2024-11-21 11:18 UTC
Labels: duplicate, IIITH
