### ISSUE TITLE
[BUG REPORT] Demonstration of Solvent Effects on Fluorescence Spectra of a Fluorophore

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2232] opened 2024-09-22 17:54 UTC
### **Bug Reported on 22 September, 23:24 GMT +5:50 in** 
Lab - Molecular Fluorescence Spectroscopy
Experiment - Demonstration of Solvent Effects on Fluorescence Spectra of a Fluorophore
**Type(s) of Issue -**
* Simulation Not Working
* Page Not Loading

Additional info- Not full screen available 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://mfs-iiith.vlabs.ac.in/exp/fluorophore/simulation.html

**Comment by shraddha** [comment] 2024-11-28 11:54
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2235 Hence closing it.

**Closed by shraddha** 2024-11-28 11:54 UTC
Labels: duplicate, IIITH
