### ISSUE TITLE
[BUG REPORT] TRANSFORMATIONS: ROTATION

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1625] opened 2024-09-02 06:57 UTC
### **Bug Reported on 2 September, 12:27 GMT +5:50 in** 
Lab - Virtual Lab
Experiment - TRANSFORMATIONS: ROTATION
**Type(s) of Issue -**

Additional info- Ambiguous instruction 2.1:  Who selects the point?  And how?

The procedure must contain statements that are in imperative form.

UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
Experiment Link - https://virtual-labs.github.io/exp-transformations-rotation-iiith/procedure.html
Email - ldc-1-cse@vlabs.ac.in
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1725260089214.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 11:20
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1626 Hence closing it.

**Closed by shraddha** 2024-11-28 11:20 UTC
Labels: duplicate, IIITH
