### ISSUE TITLE
[BUG REPORT] Virtual Labs Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3282] opened 2024-10-16 09:26 UTC
### **Bug Reported on 16 October, 14:56 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- here I initialize value with 8.8 but it give me answer in form of 8 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/simulation.html
Email - rudra24267@gmail.com

**Comment by shraddha** [comment] 2024-11-28 11:51
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1052 Hence closing it.

**Closed by shraddha** 2024-11-28 11:51 UTC
Labels: duplicate, IIITH
