### ISSUE TITLE
[BUG REPORT] Hart Straight Line Mechanism

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#188] opened 2024-03-03 12:26 UTC
### **Bug Reported on 3 March, 17:56 GMT +5:50 in** 
Lab - Mechanics of Machine II
Experiment - Hart Straight Line Mechanism
**Type(s) of Issue -**

Additional info- Who to creat simulation 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Email - santovalan192@gmail.com

**Comment by SOLVE-NITK** [comment] 2024-11-28 08:00
The issue is not relevant to the experiment. Closing the issue with the label **Inappropriate**

**Closed by SOLVE-NITK** 2024-11-28 08:00 UTC
Labels: NITK, Inappropriate
