### ISSUE TITLE
[BUG REPORT] Advanced Control Flow

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#619] opened 2024-07-24 22:24 UTC
### **Bug Reported on 25 July, 3:54 GMT +5:50 in** 
Lab - Computer programming
Experiment - Advanced Control Flow
**Type(s) of Issue -**
* Page Not Loading
* Content Not Visible

Additional info- the questions are not visible and the submit button is also not visible

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/advanced-control-flow/posttest.html

**Comment by shraddha** [comment] 2024-11-21 13:32
This bug is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/476 hence closing it.

**Closed by shraddha** 2024-11-21 13:32 UTC
Labels: duplicate, IIITH
