### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4853] opened 2024-12-18 20:12 UTC
### **Bug Reported on 19 December, 1:42 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Page Not Loading
* Content Not Visible

Additional info- Not loading 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/

**Comment by vlabiitk** [comment] 2024-12-24 06:58
Duplicate of #4857

**Closed by vlabiitk** 2024-12-24 06:58 UTC
Labels: duplicate, IITK
