### ISSUE TITLE
[BUG REPORT] Virtual Labs Path algorithms: Dijkstra's shortest path

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3973] opened 2024-11-07 08:13 UTC
### **Bug Reported on 7 November, 13:43 GMT +5:50 in** 
Lab - Data Structures - 2
Experiment - Path algorithms: Dijkstra's shortest path
**Type(s) of Issue -**
* Simulation Not Working

Additional info- When some value (letters are entered in the text box and when pressed submit nothing is happening.

UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
Experiment Link - https://ds2-iiith.vlabs.ac.in/exp/dijkstra-algorithm/dijkstras-algorithm/DijkstrasExercise.html

**Comment by shraddha** [comment] 2024-11-27 14:02
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2928 hence closing.

**Closed by shraddha** 2024-11-27 14:02 UTC
Labels: duplicate, IIITH
