### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4877] opened 2024-12-20 13:40 UTC
### **Bug Reported on 20 December, 19:10 GMT +5:0 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Page Not Loading

Additional info- Page not loading

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 06:42
Duplicate of #823

**Closed by vlabiitk** 2024-12-24 06:42 UTC
Labels: duplicate, IITK
