### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1316] opened 2024-08-23 05:42 UTC
### **Bug Reported on 23 August, 11:12 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Content Not Visible

Additional info- Content not visible 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 06:04
Duplicate of #1581

**Closed by vlabiitk** 2024-12-24 06:04 UTC
Labels: duplicate, IITK
