### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3436] opened 2024-10-19 05:53 UTC
### **Bug Reported on 19 October, 11:22 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Page Not Loading

Additional info- Page is not loading 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/simulation.html
Email - shravani.kavade@walchandsangli.ac.in

**Comment by vlabiitk** [comment] 2024-12-24 05:21
Duplicate of #836

**Closed by vlabiitk** 2024-12-24 05:21 UTC
Labels: duplicate, IITK
