### ISSUE TITLE
[BUG REPORT] Determination of Hardness in water

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3160] opened 2024-10-12 16:59 UTC
### **Bug Reported on 12 October, 21:58 GMT +5:0 in** 
Lab - Environmental Engineering 1
Experiment - Determination of Hardness in water
**Type(s) of Issue -**

Additional info- Maryam Mehreen 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://ee1-nitk.vlabs.ac.in/exp/determination-of-hardness/posttest.html
Email - maryammehreen70@gmail.com

**Comment by SOLVE-NITK** [comment] 2024-12-03 10:03
The issue is not relevant to the experiment. Closing the issue with the label 'Inappropriate'.

**Closed by SOLVE-NITK** 2024-12-03 10:03 UTC
Labels: NITK
