### ISSUE TITLE
[BUG REPORT] Virtual Labs To verify De-Morgan's theorems

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3150] opened 2024-10-11 10:19 UTC
### **Bug Reported on 11 October, 15:49 GMT +5:50 in** 
Lab - Analog and Digital Electronics I
Experiment - To verify De-Morgan's theorems
**Type(s) of Issue -**
* Simulation Not Working
* Simulation Not Working

Additional info- Even though I made everything correct about the corrections. It shows the remainder - LED is not connected to ground

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://ade-iitr.vlabs.ac.in/exp/de-morgans-theorems/simulation.html
Email - 434saikumar7pk@gmail,com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1728641966571.png" alt="Issue image">

**Comment by vlab-iitr** [comment] 2024-11-28 10:07
Closing it, as it is a duplicate of #3149

**Closed by vlab-iitr** 2024-11-28 10:07 UTC
Labels: duplicate, IITR
