### ISSUE TITLE
[BUG REPORT] Virtual Labs Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4872] opened 2024-12-20 07:13 UTC
### **Bug Reported on 20 December, 12:43 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Simulation Not Working

Additional info- for total out put is not finding for sum 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html
Email - purveshupasani@gmail.com

**Comment by shraddha** [comment] 2024-12-25 05:57
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237 Hence closing.

**Closed by shraddha** 2024-12-25 05:57 UTC
Labels: duplicate, IIITH
