### ISSUE TITLE
[BUG REPORT] Virtual Labs Recursion

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2478] opened 2024-09-27 05:25 UTC
### **Bug Reported on 27 September, 10:55 GMT +5:50 in** 
Lab - Computer programming
Experiment - Recursion
**Type(s) of Issue -**
* Simulation Not Working
* Page Not Loading

Additional info- Lag

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-recursion/simulation.html

**Comment by shraddha** [comment] 2024-11-28 03:52
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/722 hence closing it.

**Closed by shraddha** 2024-11-28 03:52 UTC
Labels: duplicate, IIITH
