### ISSUE TITLE
[BUG REPORT] Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3330] opened 2024-10-17 06:54 UTC
### **Bug Reported on 17 October, 12:24 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Incorrect Content
* Page Not Loading
* Content Not Visible
* Insufficient Content

Additional info- Shraddha testing - please delete

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/

**Comment by shraddha** [comment] 2024-11-25 14:20
The issue is created for testing, hence closing it.

**Closed by shraddha** 2024-11-25 14:20 UTC
Labels: IIITH, test
