### ISSUE TITLE
[BUG REPORT] Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4361] opened 2024-11-24 05:46 UTC
### **Bug Reported on 24 November, 11:16 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Page Not Loading

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/procedure.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1732427206851.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-25 14:19
This seems to be duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237, hence closing it.

**Closed by shraddha** 2024-11-25 14:19 UTC
Labels: duplicate, IIITH
