### ISSUE TITLE
[BUG REPORT] Virtual Labs Classes and Objects

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3477] opened 2024-10-21 06:54 UTC
### **Bug Reported on 21 October, 12:24 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Classes and Objects
**Type(s) of Issue -**

Additional info- Issue in the frontend of the page, Output div(box) is overlapping with the Step execution box 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69
Experiment Link - https://python-iitk.vlabs.ac.in/exp/classes-and-objects/simulation.html
Email - raghavsharan2016@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITK1729493694660.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-24 09:55
Duplicate of #1935

**Closed by vlabiitk** 2024-12-24 09:55 UTC
Labels: duplicate, IITK
