### ISSUE TITLE
[BUG REPORT] To study the Load Characteristics of DC shunt generator

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3994] opened 2024-11-08 04:38 UTC
### **Bug Reported on 8 November, 10:8 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - To study the Load Characteristics of DC shunt generator
**Type(s) of Issue -**
* Simulation Not Working
* Simulation Not Working

Additional info- Connection 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/load-characteristics-dc-shunt/simulation.html
Email - damur8511@gmail.com

**Comment by vlab-iitr** [comment] 2024-12-09 10:59
Closing it, as it is a duplicate of #3021

**Closed by vlab-iitr** 2024-12-09 10:59 UTC
Labels: duplicate, IITR
