### ISSUE TITLE
[BUG REPORT] Voltage regulator using operational amplifier to produce output of 12V with maximum load current of 50mA

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3087] opened 2024-10-09 10:35 UTC
### **Bug Reported on 9 October, 16:5 GMT +5:50 in** 
Lab - Analog Electronics
Experiment - Voltage regulator using operational amplifier to produce output of 12V with maximum load current of 50mA
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Incorrect Content

Additional info- Shraddha testing 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://ae-iitr.vlabs.ac.in/exp/voltage-regulator/

**Comment by vlab-iitr** [comment] 2024-11-28 09:01
Closing it, as it is a duplicate of #2991 , #2981

**Closed by vlab-iitr** 2024-11-28 09:01 UTC
Labels: duplicate, IITR
