### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4859] opened 2024-12-19 06:21 UTC
### **Bug Reported on 19 December, 11:51 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Page Not Loading

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/procedure.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITK1734589277802.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-24 06:46
Duplicate of #4877

**Closed by vlabiitk** 2024-12-24 06:46 UTC
Labels: duplicate, IITK
