### ISSUE TITLE
[BUG REPORT] Virtual Labs Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#514] opened 2024-07-18 10:28 UTC
### **Bug Reported on 18 July, 15:58 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Content Not Visible

Additional info- content of this page is not visible 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html
Email - ujjwalpathak41297@gmail.com

**Comment by vlab-iitr** [comment] 2024-12-09 05:25
Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 05:25 UTC
Labels: duplicate, IITR
