### ISSUE TITLE
[BUG REPORT] Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1287] opened 2024-08-22 05:57 UTC
### **Bug Reported on 22 August, 11:27 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- The function used to calculate area of circle needs to be changed to calculate area of semicircle i.e. half the area of circle.

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html

**Comment by shraddha** [comment] 2024-11-25 14:24
This seems to be duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237, hence closing it.

**Closed by shraddha** 2024-11-25 14:24 UTC
Labels: duplicate, IIITH
