### ISSUE TITLE
[BUG REPORT] Virtual Labs To study the Load Characteristics of DC shunt generator

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4463] opened 2024-11-29 03:03 UTC
### **Bug Reported on 29 November, 8:33 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - To study the Load Characteristics of DC shunt generator
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/load-characteristics-dc-shunt/simulation.html
Email - justarun0210@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1732849401372.png" alt="Issue image">

**Comment by vlab-iitr** [comment] 2024-12-09 11:04
Closing it, as it is a duplicate of #3021

**Closed by vlab-iitr** 2024-12-09 11:04 UTC
Labels: duplicate, IITR
