### ISSUE TITLE
[BUG REPORT] Dijkstra's Algorithm

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#301] opened 2024-06-12 21:26 UTC
### **Bug Reported on 12 June, 23:26 GMT +2:0 in** 
Lab - Virtual Lab
Experiment - Dijkstra's Algorithm
**Type(s) of Issue -**
* Simulation Not Working

Additional info- The value input is not working

UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1
Experiment Link - https://virtual-labs.github.io/exp-dsp-iiith/dijkstras-algorithm/DijkstrasPractice.html

**Comment by shraddha** [comment] 2024-11-27 13:56
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2928 hence closing.

**Closed by shraddha** 2024-11-27 13:56 UTC
Labels: duplicate, IIITH
