### ISSUE TITLE
[BUG REPORT] Virtual Labs Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3862] opened 2024-11-05 03:51 UTC
### **Bug Reported on 5 November, 9:28 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**
* Incorrect Results/Observations
* Incorrect Content
* Insufficient/Incorrect Instructions

Additional info- In operator precedence, (-) is given higher order precedence than (+) which is incorrect according to the operator precedence table displayed in your introduction. Kindly review it.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/simulation.html
Email - sachin2004tanwar@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1730778675409.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 11:48
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1052 Hence closing it.

**Closed by shraddha** 2024-11-28 11:48 UTC
Labels: duplicate, IIITH
