### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Mono-alphabetic Substitution Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#304] opened 2024-06-14 07:22 UTC
### **Bug Reported on 14 June, 12:51 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Mono-alphabetic Substitution Cipher
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- decript the below:
awbix ildxz kolf a dkzeplld afu zbjjbfm lf bj bz a rwkx iajxpobwwap zdlgbfm a ellgae. jex iajxpobwwap ykxzjblfz awbix afu zex audbjz jl exp ikppxfj buxfjbjt ipbzbz, ildolkfuxu rt exp bfarbwbjt jl pxdxdrxp a olxd. rxnlpx ipahwbfm ahat, jex iajxpobwwap jxwwz awbix jeaj lfx zbux ln jex dkzeplld hbww dagx exp jawwxp afu jex ljexp zbux hbww dagx exp zelpjxp. zex rpxagz lnn jhl obxixz npld jex dkzeplld. lfx zbux dagxz exp zepbfg zdawwxp jeaf xcxp, hebwx afljexp iakzxz exp fxig jl mplh ebme bfjl jex jpxxz, hexpx a obmxlf dbzjagxz exp nlp a zxpoxfj. hbje zldx xnnlpj, awbix rpbfmz expzxwn raig jl exp kzkaw exbmej. zex zjkdrwxz kolf a zdaww xzjajx afu kzxz jex dkzeplld jl pxaie a dlpx aooplopbajx exbmej.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 OPR/110.0.0.0
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/substitution-cipher/simulation.html

**Comment by shraddha** [comment] 2024-11-28 07:21
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/411 Hence closing.

**Closed by shraddha** 2024-11-28 07:21 UTC
Labels: duplicate, IIITH
