### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4413] opened 2024-11-27 05:41 UTC
### **Bug Reported on 27 November, 11:11 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- tool wasnt working in assignment

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/assignment.html
Email - 228x1a1245@khitguntur.ac.in

**Comment by shraddha** [comment] 2024-11-28 08:04
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/409 hence closing it.

**Closed by shraddha** 2024-11-28 08:04 UTC
Labels: duplicate, IIITH
