### ISSUE TITLE
[BUG REPORT] Recursion

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3922] opened 2024-11-06 10:14 UTC
### **Bug Reported on 6 November, 15:44 GMT +5:50 in** 
Lab - Computer programming
Experiment - Recursion
**Type(s) of Issue -**
* Incorrect Options
* Incorrect Answer
* Incorrect Answer
* Incorrect Content
* Incorrect Options

Additional info- .*

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-recursion/pretest.html

**Comment by shraddha** [comment] 2024-11-28 03:51
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/302 hence closing it.

**Closed by shraddha** 2024-11-28 03:51 UTC
Labels: duplicate, IIITH
