### ISSUE TITLE
[BUG REPORT] DESIGN OF DIGITAL CIRCUITS USING VERILOG

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4044] opened 2024-11-11 01:28 UTC
### **Bug Reported on 11 November, 6:58 GMT +5:50 in** 
Lab - Virtual Lab
Experiment - DESIGN OF DIGITAL CIRCUITS USING VERILOG
**Type(s) of Issue -**
* Content Not Visible

Additional info- No issues 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
Experiment Link - https://virtual-labs.github.io/exp-digital-circuits-verilog-iiith/practice.html
Email - devibaghyasri@gmail.com

**Comment by shraddha** [comment] 2024-11-27 13:47
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4045 hence closing.

**Closed by shraddha** 2024-11-27 13:47 UTC
Labels: duplicate, IIITH
