### ISSUE TITLE
[BUG REPORT] Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#253] opened 2024-05-09 03:17 UTC
### **Bug Reported on 9 May, 8:47 GMT +5:50 in** 
Lab - Computer Programming
Experiment - Expression Evaluation
**Type(s) of Issue -**
* Page Not Loading

Additional info- quiz not submit 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/pretest.html

**Comment by shraddha** [comment] 2024-11-19 14:11
Closing the issue as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/250

**Closed by shraddha** 2024-11-19 14:11 UTC
Labels: duplicate, IIITH
