### ISSUE TITLE
[BUG REPORT] Specific Gravity

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2931] opened 2024-10-07 05:02 UTC
### **Bug Reported on 7 October, 10:32 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Specific Gravity
**Type(s) of Issue -**
* Incorrect Content
* Incorrect Content
* Insufficient Content
* Page Not Loading
* Content Not Visible

Additional info- we are disappointed to use virtual lap.so close the system

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/specific-gravity/theory.html
Email - avinashraj2102@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1728277340231.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 14:19
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4327 Hence closing.

**Closed by shraddha** 2024-11-28 14:19 UTC
Labels: duplicate, IIITH
