### ISSUE TITLE
[BUG REPORT] Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1342] opened 2024-08-23 05:53 UTC
### **Bug Reported on 23 August, 11:23 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Page Not Loading
* Insufficient Content

Additional info- Poor GUI

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/

**Comment by vlabiitk** [comment] 2024-12-24 06:31
Duplicate of #1317

**Closed by vlabiitk** 2024-12-24 06:31 UTC
Labels: duplicate, IITK
