### ISSUE TITLE
[BUG REPORT] Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2329] opened 2024-09-24 09:13 UTC
### **Bug Reported on 24 September, 14:43 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**
* Incorrect Answer

Additional info- Correct answer of question number 6 is o.8 instead of 4

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/pretest.html
Email - rohitsargara2004@gmail.com, talksnik@gmail.com, tripathisk872@gmail.com, dakshhere909@gmail.com, kk8723442@!gmail.com,varugehot6@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/COEP1727168999309.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 11:46
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/696 Hence closing it.

**Closed by shraddha** 2024-11-28 11:46 UTC
Labels: duplicate, IIITH
