### ISSUE TITLE
[BUG REPORT] To determine the specific rotation of a sugar using a polarimeter

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4323] opened 2024-11-21 14:49 UTC
### **Bug Reported on 21 November, 20:19 GMT +5:50 in** 
Lab - Circular Dichronism Spectroscopy
Experiment - To determine the specific rotation of a sugar using a polarimeter
**Type(s) of Issue -**
* Simulation Not Working

Additional info- This polarimeter is not working 
I am not able to do anything 

UserAgent: Mozilla/5.0 (Linux; U; Android 14; en-gb; RMX3392 Build/UKQ1.230924.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.88 Mobile Safari/537.36 HeyTapBrowser/45.11.5.1
Experiment Link - https://cds-iiith.vlabs.ac.in/exp/rotation-of-sugar/simulation.html

**Comment by shraddha** [comment] 2024-11-28 08:26
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4239 hence closing it.

**Closed by shraddha** 2024-11-28 08:26 UTC
Labels: duplicate, IIITH
