### ISSUE TITLE
[BUG REPORT] Bernoulli's Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4788] opened 2024-12-15 16:08 UTC
### **Bug Reported on 15 December, 21:38 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Bernoulli's Experiment
**Type(s) of Issue -**
* Insufficient Content

Additional info- Not calculate the value and data

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/bernoullis/observations.html

**Comment by shraddha** [comment] 2024-12-16 19:48
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3735 Hence closing.

**Closed by shraddha** 2024-12-16 19:48 UTC
Labels: duplicate, IIITH
