### ISSUE TITLE
[BUG REPORT] Virtual Labs To determine the specific rotation of a sugar using a polarimeter

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2056] opened 2024-09-17 14:48 UTC
### **Bug Reported on 17 September, 20:18 GMT +5:50 in** 
Lab - Circular Dichronism Spectroscopy
Experiment - To determine the specific rotation of a sugar using a polarimeter
**Type(s) of Issue -**
* Simulation Not Working

Additional info- nothing i click on is working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Experiment Link - https://cds-iiith.vlabs.ac.in/exp/rotation-of-sugar/simulation.html

**Comment by shraddha** [comment] 2024-11-28 08:24
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4239 hence closing it.

**Closed by shraddha** 2024-11-28 08:24 UTC
Labels: duplicate, IIITH
