### ISSUE TITLE
[BUG REPORT] Water Content

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4550] opened 2024-12-03 04:49 UTC
### **Bug Reported on 3 December, 10:19 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Water Content
**Type(s) of Issue -**
* Incorrect Results/Observations
* Simulation Not Working

Additional info- Jsjs

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/water-content/simulation.html

**Comment by shraddha** [comment] 2024-12-04 05:59
Though this bug seems like duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1043, as the additional information with the bug seems to be invalid, marking this bug as invalid and hence closing it.

**Closed by shraddha** 2024-12-04 05:59 UTC
Labels: invalid, IIITH
