### ISSUE TITLE
[BUG REPORT] Introduction to the fluorescence spectroscopy principle

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4724] opened 2024-12-12 01:47 UTC
### **Bug Reported on 12 December, 7:17 GMT +5:50 in** 
Lab - Molecular Fluorescence Spectroscopy
Experiment - Introduction to the fluorescence spectroscopy principle
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Not working 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://mfs-iiith.vlabs.ac.in/exp/fluorescence-spectroscopy-principle/simulation.html

**Comment by shraddha** [comment] 2024-12-14 11:10
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1610 Hence closing.

**Closed by shraddha** 2024-12-14 11:10 UTC
Labels: duplicate, IIITH
