### ISSUE TITLE
[BUG REPORT] Virtual Labs Hash Tables

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2514] opened 2024-09-27 11:45 UTC
### **Bug Reported on 27 September, 17:15 GMT +5:50 in** 
Lab - Virtual Lab
Experiment - Hash Tables
**Type(s) of Issue -**
* Content Not Visible

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://virtual-labs.github.io/exp-hashtables-iiith/hash-tables/ht_exercise.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1727437546261.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 08:08
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2513 hence closing it.

**Closed by shraddha** 2024-11-28 08:08 UTC
Labels: duplicate, IIITH
