### ISSUE TITLE
[BUG REPORT] Breaking the Mono-alphabetic Substitution Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#221] opened 2024-04-29 05:17 UTC
### **Bug Reported on 29 April, 10:47 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Mono-alphabetic Substitution Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- After writing solution key,it doesn't give correct value

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/substitution-cipher/simulation.html
Email - anonymousshetty2003@gmail.com

**Comment by shraddha** [comment] 2024-11-28 07:21
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/411 Hence closing.

**Closed by shraddha** 2024-11-28 07:21 UTC
Labels: duplicate, IIITH
