### ISSUE TITLE
[BUG REPORT] Virtual Labs Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#758] opened 2024-07-29 10:45 UTC
### **Bug Reported on 29 July, 16:15 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Simulation Not Working

Additional info- check answer is not working... 
in html " id ='notification' " in <p> tag is missing...
in js this code mentions show answer when notification id is there in html
 "	if(trim(userAns) == trim(answer)) {
		document.getElementById("notification").innerHTML = "CORRECT!!";
	} else {
		document.getElementById("notification").innerHTML = "Sorry, answer is wrong. Please try again.";
	} "

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html
Email - soni.darshan0209@gmail.com, djrajput2004@gmail.com

**Comment by shraddha** [comment] 2024-11-19 15:08
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 15:08 UTC
Labels: duplicate, IIITH
