### ISSUE TITLE
[BUG REPORT] Familiarisation with General Bread Board

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2956] opened 2024-10-07 10:02 UTC
### **Bug Reported on 7 October, 15:32 GMT +5:50 in** 
Lab - Analog and Digital Electronics I
Experiment - Familiarisation with General Bread Board
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Can't connect the components 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://ade-iitr.vlabs.ac.in/exp/general-bread-board/simulation.html

**Comment by vlab-iitr** [comment] 2024-11-29 06:48
Closing it, as it is a duplicate of #2277 & #1801

**Closed by vlab-iitr** 2024-11-29 06:48 UTC
Labels: duplicate, IITR
