### ISSUE TITLE
[BUG REPORT] Merge Sort

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3006] opened 2024-10-08 07:12 UTC
### **Bug Reported on 8 October, 22:52 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Merge Sort
**Type(s) of Issue -**
* Incorrect Content

Additional info- not correct answer 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/merge-sort/index.html

**Comment by shraddha** [comment] 2024-11-23 04:24
The issue is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2075, hence closing it.

**Closed by shraddha** 2024-11-23 04:24 UTC
Labels: duplicate, IIITH
