### ISSUE TITLE
[BUG REPORT] Virtual Labs Tree Traversal

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3816] opened 2024-11-02 16:24 UTC
### **Bug Reported on 2 November, 12:24 GMT -4:0 in** 
Lab - Data Structures - 1
Experiment - Tree Traversal
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- Pre order traversal is supposed to be curr left right

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/tree-traversal/depth-first-traversal/dft-practice.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1730564236238.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-12-14 11:08
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4661 Hence closing.

**Closed by shraddha** 2024-12-14 11:08 UTC
Labels: bug, duplicate, IIITH
