### ISSUE TITLE
[BUG REPORT] Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4229] opened 2024-11-16 13:54 UTC
### **Bug Reported on 16 November, 19:24 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- Iam not getting exactly why my answer is incorrect as it is not taking *0.5 with the functions 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html

**Comment by shraddha** [comment] 2024-11-25 14:22
This seems to be duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237, hence closing it.

**Closed by shraddha** 2024-11-25 14:22 UTC
Labels: duplicate, IIITH
