### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#823] opened 2024-08-01 10:28 UTC
### **Bug Reported on 1 August, 15:58 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Content Not Visible

Additional info- Insufficient content 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/

**Comment by vlabiitk** [comment] 2024-12-24 04:48
Duplicate of #836

**Closed by vlabiitk** 2024-12-24 04:48 UTC
Labels: duplicate, IITK
