### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#428] opened 2024-07-16 04:35 UTC
### **Bug Reported on 16 July, 10:5 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Insufficient Content

Additional info- uj8jh98-]=

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/theory.html
Email - 98u7yh87y
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITK1721104557309.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-24 05:20
Duplicate of #429

**Closed by vlabiitk** 2024-12-24 05:20 UTC
Labels: duplicate, IITK
