### ISSUE TITLE
[BUG REPORT] Mathematical operations using Op-Amp

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1713] opened 2024-09-04 08:10 UTC
### **Bug Reported on 4 September, 13:40 GMT +5:50 in** 
Lab - Analog and Digital Electronics II
Experiment - Mathematical operations using Op-Amp
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Nothing 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://ade2-iitr.vlabs.ac.in/exp/mathematical-operations/simulation.html

**Comment by vlab-iitr** [comment] 2024-11-29 05:19
Closing it, as it is a duplicate of #1719

**Closed by vlab-iitr** 2024-11-29 05:19 UTC
Labels: duplicate, IITR
