### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4414] opened 2024-11-27 05:46 UTC
### **Bug Reported on 27 November, 11:16 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- bad

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/simulation.html

**Comment by shraddha** [comment] 2024-11-28 08:05
Duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/371 hence closing.

**Closed by shraddha** 2024-11-28 08:05 UTC
Labels: duplicate, IIITH
