### ISSUE TITLE
[BUG REPORT] Strings

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1297] opened 2024-08-22 06:16 UTC
### **Bug Reported on 22 August, 11:46 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Strings
**Type(s) of Issue -**
* Incorrect Question

Additional info- question ) what arithmetic operator are incorrect in python
correct answer all the mentioned

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/strings/pretest.html

**Comment by vlabiitk** [comment] 2024-12-20 12:18
This issue is duplicate of #3489.

**Closed by vlabiitk** 2024-12-20 12:18 UTC
Labels: duplicate, IITK
