### ISSUE TITLE
[BUG REPORT] Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4376] opened 2024-11-25 07:52 UTC
### **Bug Reported on 25 November, 13:22 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Voltage can't set and field windings does not move and roter remains off

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html

**Comment by vlab-iitr** [comment] 2024-12-09 06:20
Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 06:20 UTC
Labels: duplicate, IITR
