### ISSUE TITLE
[BUG REPORT] Virtual Labs Depth First Search

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2127] opened 2024-09-19 16:43 UTC
### **Bug Reported on 19 September, 22:13 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Depth First Search
**Type(s) of Issue -**
* Simulation Not Working

Additional info- After I have selected the node then start then it is not showing the traversal of the graph.So,I kindly request you to please fix this bug as soon as possible

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/depth-first-search/dfs/dfs-demo.html

**Comment by shraddha** [comment] 2024-11-27 15:21
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3582, hence closing it.

**Closed by shraddha** 2024-11-27 15:21 UTC
Labels: duplicate, IIITH
