### ISSUE TITLE
[BUG REPORT] Virtual Labs Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1653] opened 2024-09-02 09:52 UTC
### **Bug Reported on 2 September, 15:22 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions

Additional info- function call not possible for semi circles 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html

**Comment by shraddha** [comment] 2024-11-25 14:24
This seems to be duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237, hence closing it.

**Closed by shraddha** 2024-11-25 14:24 UTC
Labels: duplicate, IIITH
