### ISSUE TITLE
[BUG REPORT] To design a Touch sensor circuit using Bipolar Junction Transistor (BJT)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4321] opened 2024-11-21 13:23 UTC
### **Bug Reported on 21 November, 18:53 GMT +5:50 in** 
Lab - Analog and Digital Electronics II
Experiment - To design a Touch sensor circuit using Bipolar Junction Transistor (BJT)
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Hi

UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/130.0.6723.90 Mobile/15E148 Safari/604.1
Experiment Link - https://ade2-iitr.vlabs.ac.in/exp/bjt-transistor/simulation.html

**Comment by vlab-iitr** [comment] 2024-11-29 05:49
Closing it, as it is a duplicate of #4320

**Closed by vlab-iitr** 2024-11-29 05:49 UTC
Labels: duplicate, IITR
