### ISSUE TITLE
[BUG REPORT] To study the Load Characteristics of DC shunt generator

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3212] opened 2024-10-15 05:04 UTC
### **Bug Reported on 15 October, 10:34 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - To study the Load Characteristics of DC shunt generator
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- Hh

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/load-characteristics-dc-shunt/simulation.html

**Comment by vlab-iitr** [comment] 2024-12-09 10:53
Closing it, as it is a duplicate of #3021

**Closed by vlab-iitr** 2024-12-09 10:53 UTC
Labels: duplicate, IITR
