### ISSUE TITLE
[BUG REPORT] Strings

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2705] opened 2024-10-03 10:18 UTC
### **Bug Reported on 3 October, 15:48 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Strings
**Type(s) of Issue -**
* Page Not Loading

Additional info- Not reloding page

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/strings/pretest.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1727949834718.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-20 12:17
This issue is a duplicate of #3245.

**Closed by vlabiitk** 2024-12-20 12:17 UTC
Labels: IITK
