### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#917] opened 2024-08-06 08:59 UTC
### **Bug Reported on 6 August, 14:29 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Simulation Not Working
* Page Not Loading

Additional info- simulation not working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1722934789354.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-21 11:20
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/371 hence closing it.

**Closed by shraddha** 2024-11-21 11:20 UTC
Labels: duplicate, IIITH
