### ISSUE TITLE
[BUG REPORT] Compaction Test

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3606] opened 2024-10-24 06:50 UTC
### **Bug Reported on 24 October, 12:19 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Compaction Test
**Type(s) of Issue -**
* Simulation Not Working
* Page Not Loading

Additional info- Simulation not working and page not loading

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/compaction-test/simulation.html
Email - rahulkumar79798017@gmail.com

**Comment by shraddha** [comment] 2024-11-29 11:52
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2034 Hence closing it.

**Closed by shraddha** 2024-11-29 11:52 UTC
Labels: duplicate, IIITH
