### ISSUE TITLE
[BUG REPORT] Message Authentication Codes

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3405] opened 2024-10-18 08:16 UTC
### **Bug Reported on 18 October, 13:46 GMT +5:50 in** 
Lab - Cryptography
Experiment - Message Authentication Codes
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- it is difficult to verfy and to find out where it is located

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/message-authentication-codes/

**Comment by shraddha** [comment] 2024-11-28 14:28
Duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1065 hence closing.

**Closed by shraddha** 2024-11-28 14:28 UTC
Labels: duplicate, IIITH
