### ISSUE TITLE
[BUG REPORT] Virtual Labs Schematic Design Of D-Latch and D-Flip Flop

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4911] opened 2024-12-24 07:07 UTC
### **Bug Reported on 24 December, 12:37 GMT +5:50 in** 
Lab - VLSI
Experiment - Schematic Design Of D-Latch and D-Flip Flop
**Type(s) of Issue -**
* Content Not Visible

Additional info- Plain white screen is seen

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://cse14-iiith.vlabs.ac.in/exp/d-latch-and-d-flip-flop/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1735024049488.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-12-25 05:52
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3145 Hence closing.

**Closed by shraddha** 2024-12-25 05:52 UTC
Labels: duplicate, IIITH
