### ISSUE TITLE
[BUG REPORT] File Operators

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3419] opened 2024-10-18 09:25 UTC
### **Bug Reported on 18 October, 14:55 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - File Operators
**Type(s) of Issue -**
* Page Not Loading
* Content Not Visible

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/file-operators
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITK1729243539361.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-20 12:14
This issue is a duplicate of #3422.

**Closed by vlabiitk** 2024-12-20 12:14 UTC
Labels: duplicate, IITK
