### ISSUE TITLE
[BUG REPORT] Familiarization with the fluorescence Instrumentation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1936] opened 2024-09-11 12:28 UTC
### **Bug Reported on 11 September, 20:28 GMT +8:0 in** 
Lab - Molecular Fluorescence Spectroscopy
Experiment - Familiarization with the fluorescence Instrumentation
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Nothing is showing even when I reset

UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1
Experiment Link - https://mfs-iiith.vlabs.ac.in/exp/fluorescence-instrumentation/simulation.html

**Comment by shraddha** [comment] 2024-11-28 11:28
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1666 Hence closing.

**Closed by shraddha** 2024-11-28 11:28 UTC
Labels: duplicate, IIITH
