### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3047] opened 2024-10-09 04:14 UTC
### **Bug Reported on 9 October, 9:44 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Simulation Not Working
* Page Not Loading

Additional info- Simulation is not correct working

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/simulation.html
Email - sunilbiranje55@gmail.com

**Comment by vlabiitk** [comment] 2024-12-24 05:23
Duplicate of #836

**Closed by vlabiitk** 2024-12-24 05:23 UTC
Labels: duplicate, IITK
