### ISSUE TITLE
[BUG REPORT] Water Content

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1583] opened 2024-08-31 01:23 UTC
### **Bug Reported on 31 August, 6:53 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Water Content
**Type(s) of Issue -**
* Simulation Not Working
* Insufficient/Incorrect Instructions
* Incorrect Results/Observations
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- Do

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/water-content/simulation.html

**Comment by shraddha** [comment] 2024-11-28 14:58
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1043 Hence closing.

**Closed by shraddha** 2024-11-28 14:58 UTC
Labels: duplicate, IIITH
