### ISSUE TITLE
[BUG REPORT] Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4223] opened 2024-11-16 07:33 UTC
### **Bug Reported on 16 November, 13:3 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**
* Content Not Visible

Additional info- Na

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/
Email - devedisiddharthsuryaprakash@amityonline.com

**Comment by shraddha** [comment] 2024-11-28 11:48
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1052 Hence closing it.

**Closed by shraddha** 2024-11-28 11:48 UTC
Labels: duplicate, IIITH
