### ISSUE TITLE
[BUG REPORT] Brinell Hardness Test

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1939] opened 2024-09-11 14:26 UTC
### **Bug Reported on 11 September, 8:26 GMT -6:0 in** 
Lab - Virtual Strength of Materials Lab
Experiment - Brinell Hardness Test
**Type(s) of Issue -**

Additional info- Simulación working

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://sm-nitk.vlabs.ac.in/exp/brinell-hardness-test/simulation.html

**Comment by SOLVE-NITK** [comment] 2024-11-29 07:49
Issue provided is not a bug. Hence closing the issue with label **Inapropriate**

**Comment by shraddha** [comment] 2024-12-05 14:32
Please review the labeling by referring to the section 'Categorize the bug' from [Bug Management Process](https://vlead.vlabs.ac.in/development/#bug-processing-guide). This bug seems to fall into either of these categories - invalid or Not Reproducible. Hence removing the inappropriate label and reopening the bug for reassignment of right label.

**Comment by SOLVE-NITK** [comment] 2024-12-09 10:25
None of the issues seem to fit the content with the experiment. Hence marking it as invalid and closing it.

**Closed by SOLVE-NITK** 2024-12-09 10:25 UTC
Labels: invalid, NITK
