### ISSUE TITLE
[BUG REPORT] Virtual Labs Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#598] opened 2024-07-23 09:13 UTC
### **Bug Reported on 23 July, 14:43 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Simulation Not Working

Additional info- the answer of the question is not showing
plz kindly look after it so that it can be helpfull

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html
Email - ronak.16982@sakec.ac.in
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1721726037490.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-19 14:44
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 14:44 UTC
Labels: duplicate, IIITH
