### ISSUE TITLE
[BUG REPORT] Structures

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4657] opened 2024-12-09 14:05 UTC
### **Bug Reported on 9 December, 19:35 GMT +5:50 in** 
Lab - Computer programming
Experiment - Structures
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation not working 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/structures/simulation.html

**Comment by shraddha** [comment] 2024-12-10 06:44
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2026 Hence closing.

**Closed by shraddha** 2024-12-10 06:44 UTC
Labels: duplicate, IIITH
