### ISSUE TITLE
[BUG REPORT] Virtual Labs Rim Type Flywheel

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1548] opened 2024-08-29 10:04 UTC
### **Bug Reported on 29 August, 15:34 GMT +5:50 in** 
Lab - Dynamics of Machine
Experiment - Rim Type Flywheel
**Type(s) of Issue -**
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Content Not Visible
* Incorrect Content
* Simulation Not Working

Additional info- rhgdgf xvf cdgb

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://dom-nitk.vlabs.ac.in/exp/rim-type-flywheel/simulation.html
Email - ydhehtb
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1724925865236.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment] 2024-11-28 07:55
The issue is not relevant to the experiment. Closing the issue with the label **Inappropriate**

**Comment by shraddha** [comment] 2024-12-05 14:34
Please review the labeling by referring to the section 'Categorize the bug' from [Bug Management Process](https://vlead.vlabs.ac.in/development/#bug-processing-guide). This bug seems to fall into either of these categories - invalid or Not Reproducible. Hence removing the inappropriate label and reopening the bug for reassignment of right label.

**Closed** 2024-12-09 10:36 UTC
Labels: invalid, NITK
