### ISSUE TITLE
[BUG REPORT] Virtual Labs Mouthpieces Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4445] opened 2024-11-28 06:42 UTC
### **Bug Reported on 28 November, 12:12 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Mouthpieces Experiment
**Type(s) of Issue -**
* Simulation Not Working
* Simulation Not Working

Additional info- Stimulation not working at all

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/mouthpieces/simulation.html

**Comment by shraddha** [comment] 2024-11-28 14:30
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3277 Hence closing.

**Closed by shraddha** 2024-11-28 14:30 UTC
Labels: duplicate, IIITH
