### ISSUE TITLE
[BUG REPORT] Virtual Labs Arrays

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3917] opened 2024-11-06 09:58 UTC
### **Bug Reported on 6 November, 15:28 GMT +5:50 in** 
Lab - Computer programming
Experiment - Arrays
**Type(s) of Issue -**
* Simulation Not Working

Additional info- not responding properly

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/arrays/simulation.html
Email - pranavmurali05@gmail.com

**Comment by shraddha** [comment] 2024-11-27 15:43
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1469, hence closing it.

**Closed by shraddha** 2024-11-27 15:43 UTC
Labels: duplicate, IIITH
