### ISSUE TITLE
[BUG REPORT] Bernoulli's Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4348] opened 2024-11-23 08:25 UTC
### **Bug Reported on 23 November, 13:54 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Bernoulli's Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Stimulation not working 

UserAgent: Mozilla/5.0 (iPad; CPU OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/129.0.6668.69 Mobile/15E148 Safari/604.1
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/bernoullis/simulation.html

**Comment by shraddha** [comment] 2024-11-27 13:24
This is the duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3735, and hence closing.

**Closed by shraddha** 2024-11-27 13:24 UTC
Labels: duplicate, IIITH
