### ISSUE TITLE
[BUG REPORT] Data Types

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1467] opened 2024-08-27 06:01 UTC
### **Bug Reported on 27 August, 11:31 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Data Types
**Type(s) of Issue -**
* Page Not Loading

Additional info- Simulation not loading

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/data-types/

**Comment by vlabiitk** [comment] 2024-12-24 10:09
Duplicate of #2132

**Closed by vlabiitk** 2024-12-24 10:09 UTC
Labels: duplicate, IITK
