### ISSUE TITLE
[BUG REPORT] Stacks Queues

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4047] opened 2024-11-11 05:10 UTC
### **Bug Reported on 11 November, 10:40 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Stacks Queues
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- page not working corrrect it wasted my time 

UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/stacks-queues/stacks/index.html

**Comment by shraddha** [comment] 2024-11-27 14:32
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2473 hence closing it.

**Closed by shraddha** 2024-11-27 14:32 UTC
Labels: duplicate, IIITH
