### ISSUE TITLE
[BUG REPORT] Virtual Labs Tree Traversal

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4777] opened 2024-12-14 08:41 UTC
### **Bug Reported on 14 December, 10:41 GMT +2:0 in** 
Lab - Data Structures - 1
Experiment - Tree Traversal
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- The tree is the other way around and it doesn't always respect the order of the numbers.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/tree-traversal/depth-first-traversal/dft-practice.html

**Comment by shraddha** [comment] 2024-12-14 11:08
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4661 Hence closing.

**Closed by shraddha** 2024-12-14 11:08 UTC
Labels: duplicate, IIITH
