### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1888] opened 2024-09-10 09:29 UTC
### **Bug Reported on 10 September, 14:59 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- not giving proper or right answers

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/simulation.html

**Comment by shraddha** [comment] 2024-11-21 11:21
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/371 hence closing it.

**Closed by shraddha** 2024-11-21 11:21 UTC
Labels: duplicate, IIITH
