### ISSUE TITLE
[BUG REPORT] Virtual Labs Stacks Queues

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2032] opened 2024-09-14 16:16 UTC
### **Bug Reported on 14 September, 21:55 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Stacks Queues
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- Stack - Linked list - pop operation is not working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/stacks-queues/stacks/stack-linkedlist.html

**Comment by shraddha** [comment] 2024-11-27 14:34
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2473 hence closing it.

**Closed by shraddha** 2024-11-27 14:34 UTC
Labels: duplicate, IIITH
