### ISSUE TITLE
[BUG REPORT] Stacks Queues

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3340] opened 2024-10-17 08:01 UTC
### **Bug Reported on 17 October, 13:31 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Stacks Queues
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Content Not Visible

Additional info- UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/stacks-queues/index.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1729152103003.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-27 14:31
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2473 hence closing it.

**Closed by shraddha** 2024-11-27 14:31 UTC
Labels: duplicate, IIITH
