### ISSUE TITLE
[BUG REPORT] Bernoulli's Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4893] opened 2024-12-22 05:17 UTC
### **Bug Reported on 22 December, 9:17 GMT +4:0 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Bernoulli's Experiment
**Type(s) of Issue -**
* Simulation Not Working
* Content Not Visible

Additional info- We can only see the water levels but no values are visible. I.e. there are no numbers displayed.

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/bernoullis/simulation.html
Email - vikasjsheth@gmail.com

**Comment by shraddha** [comment] 2024-12-25 05:49
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3735 Hence closing.

**Closed by shraddha** 2024-12-25 05:49 UTC
Labels: duplicate, IIITH
