### ISSUE TITLE
[BUG REPORT] Basic Control Flow

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4394] opened 2024-11-26 09:13 UTC
### **Bug Reported on 27 November, 3:17 GMT +5:50 in** 
Lab - Computer programming
Experiment - Basic Control Flow
**Type(s) of Issue -**
* Incorrect Answer

Additional info- on the question no.9 the correct answer is option (a) Hi

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/basic-control-flow/pretest.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1732612415756.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-26 15:55
This bug is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/233 and hence closing.

**Closed by shraddha** 2024-11-26 15:55 UTC
Labels: duplicate, IIITH
