### ISSUE TITLE
[BUG REPORT] Virtual Labs Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1235] opened 2024-08-21 05:05 UTC
### **Bug Reported on 21 August, 10:37 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Insufficient/Incorrect Instructions
* Simulation Not Working
* Incorrect Results/Observations
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- not working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITK1724216739543.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-24 06:33
Duplicate of #1234

**Closed by vlabiitk** 2024-12-24 06:33 UTC
Labels: duplicate, IITK
