### ISSUE TITLE
[BUG REPORT] Virtual Labs Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1923] opened 2024-09-11 05:51 UTC
### **Bug Reported on 11 September, 11:21 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Submit button issue,
on clicking it's not responding

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html
Email - kohliprachi26@gmail.com

**Comment by shraddha** [comment] 2024-11-19 15:18
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 15:18 UTC
Labels: duplicate, IIITH
