### ISSUE TITLE
[BUG REPORT] Astable and monostable multivibrator using IC 555

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3154] opened 2024-10-11 20:15 UTC
### **Bug Reported on 12 October, 1:45 GMT +5:50 in** 
Lab - Analog Electronics
Experiment - Astable and monostable multivibrator using IC 555
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- Dvjjgf

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://ae-iitr.vlabs.ac.in/exp/astable-monostable-multivibrator/procedure.html
Email - pratikshapokale77@gmail.com

**Comment by vlab-iitr** [comment] 2024-11-28 09:06
Closing it, as it is a duplicate of #3153

**Closed by vlab-iitr** 2024-11-28 09:06 UTC
Labels: duplicate, IITR
