### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Mono-alphabetic Substitution Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#413] opened 2024-07-15 09:31 UTC
### **Bug Reported on 15 July, 15:6 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Mono-alphabetic Substitution Cipher
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations

Additional info- There is issue in Part3 of simulation in which solution key is always showing incorrect

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/substitution-cipher/simulation.html

**Comment by shraddha** [comment] 2024-11-28 07:20
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/411 Hence closing.

**Closed by shraddha** 2024-11-28 07:20 UTC
Labels: duplicate, IIITH
