### ISSUE TITLE
[BUG REPORT] Virtual Labs Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3603] opened 2024-10-24 06:36 UTC
### **Bug Reported on 24 October, 12:6 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Simulation Not Working

Additional info- not working

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 06:11
#Duplicate of 3608

**Closed by vlabiitk** 2024-12-24 06:11 UTC
Labels: duplicate, IITK
