### ISSUE TITLE
[BUG REPORT] Virtual Labs Path algorithms: Dijkstraâs shortest path

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2926] opened 2024-10-07 04:14 UTC
### **Bug Reported on 7 October, 9:48 GMT +5:50 in** 
Lab - Data Structures - 2
Experiment - Path algorithms: Dijkstraâs shortest path
**Type(s) of Issue -**
* Simulation Not Working

Additional info- node submit button not working unable to perform the experiment 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Experiment Link - https://ds2-iiith.vlabs.ac.in/exp/dijkstra-algorithm/dijkstras-algorithm/DijkstrasExercise.html

**Comment by shraddha** [comment] 2024-11-27 13:57
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2928 hence closing.

**Closed by shraddha** 2024-11-27 13:57 UTC
Labels: duplicate, IIITH
