### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3604] opened 2024-10-24 06:38 UTC
### **Bug Reported on 24 October, 12:8 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Incorrect Options
* Incorrect Options

Additional info- UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/pretest.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITK1729751899137.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-24 05:58
Duplicate of #818

**Closed by vlabiitk** 2024-12-24 05:58 UTC
Labels: duplicate, IITK
