### ISSUE TITLE
[BUG REPORT] Grain Size Distribution

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3671] opened 2024-10-25 13:02 UTC
### **Bug Reported on 25 October, 18:32 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Grain Size Distribution
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation not working

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/grain-size-distribution/simulation.html

**Comment by shraddha** [comment] 2024-11-28 15:16
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2360 Hence closing.

**Closed by shraddha** 2024-11-28 15:16 UTC
Labels: duplicate, IIITH
