### ISSUE TITLE
[BUG REPORT] Carey Foster’s Bridge to Measure Specific Resistance of Material

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3213] opened 2024-10-15 05:18 UTC
### **Bug Reported on 15 October, 10:48 GMT +5:50 in** 
Lab - Basics of Physics
Experiment - Carey Foster’s Bridge to Measure Specific Resistance of Material
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Issues
Simulation Not Working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://bop-iitk.vlabs.ac.in/exp/carey-foster-bridge/simulation.html

**Comment by vlabiitk** [comment] 2024-12-26 11:09
Duplicate of #854

**Closed by vlabiitk** 2024-12-26 11:09 UTC
Labels: duplicate, IITK
