### ISSUE TITLE
[BUG REPORT] Virtual Labs Classes and Objects

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3605] opened 2024-10-24 06:48 UTC
### **Bug Reported on 24 October, 12:18 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Classes and Objects
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading

Additional info- bad

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/classes-and-objects/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 09:55
Duplicate of #1935

**Closed by vlabiitk** 2024-12-24 09:55 UTC
Labels: duplicate, IITK
