### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4798] opened 2024-12-16 05:09 UTC
### **Bug Reported on 16 December, 10:39 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Simulation Not Working

Additional info- In simulation form we are not getting the option in which we can select the different type of operations

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 06:09
Duplicate of #836

**Closed by vlabiitk** 2024-12-24 06:09 UTC
Labels: duplicate, IITK
