### ISSUE TITLE
[BUG REPORT] Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1075] opened 2024-08-12 11:24 UTC
### **Bug Reported on 12 August, 16:54 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Incorrect Content

Additional info- teach properly for pretest, pretest content missing how answer me , u tell

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/posttest.html
Email - lenoymenezes182@gmail.com

**Comment by vlabiitk** [comment] 2024-12-24 06:34
Duplicate of #1234

**Closed by vlabiitk** 2024-12-24 06:34 UTC
Labels: duplicate, IITK
