### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Mono-alphabetic Substitution Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#992] opened 2024-08-08 07:22 UTC
### **Bug Reported on 8 August, 12:50 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Mono-alphabetic Substitution Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- Their is no instruction for alphabet which is not replace by any other alphabet so we unable to find the solution key

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/substitution-cipher/simulation.html
Email - shahumohit89@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1723101731637.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 07:30
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/411 Hence closing.

**Closed by shraddha** 2024-11-28 07:30 UTC
Labels: duplicate, IIITH
