### ISSUE TITLE
[BUG REPORT] To determine the specific rotation of a sugar using a polarimeter

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#784] opened 2024-07-31 04:17 UTC
### **Bug Reported on 31 July, 9:47 GMT +5:50 in** 
Lab - Circular Dichronism Spectroscopy
Experiment - To determine the specific rotation of a sugar using a polarimeter
**Type(s) of Issue -**
* Simulation Not Working

Additional info- No further procedure

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://cds-iiith.vlabs.ac.in/exp/rotation-of-sugar/simulation.html

**Comment by shraddha** [comment] 2024-11-28 08:23
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4239 hence closing it.

**Closed by shraddha** 2024-11-28 08:23 UTC
Labels: duplicate, IIITH
