### ISSUE TITLE
[BUG REPORT] Constructors and Inheritance

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4392] opened 2024-11-26 08:16 UTC
### **Bug Reported on 26 November, 13:46 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Constructors and Inheritance
**Type(s) of Issue -**
* Content Not Visible

Additional info- Website not responsive on Mobile device 

UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/302.0.603406840 Mobile/15E148 Safari/604.1
Experiment Link - https://python-iitk.vlabs.ac.in/exp/constructors-and-inheritance/simulation.html

**Comment by vlabiitk** [comment] 2024-12-20 12:40
Duplicate of #1319

**Closed by vlabiitk** 2024-12-20 12:40 UTC
Labels: duplicate, IITK
