### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1757] opened 2024-09-05 11:19 UTC
### **Bug Reported on 5 September, 16:49 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Page Not Loading
* Insufficient/Incorrect Instructions
* Content Not Visible
* Incorrect Content

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/assignment.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1725535178885.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-21 11:23
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/409 Hence closing it.

**Closed by shraddha** 2024-11-21 11:23 UTC
Labels: duplicate, IIITH
