### ISSUE TITLE
[BUG REPORT] Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1233] opened 2024-08-21 04:53 UTC
### **Bug Reported on 21 August, 10:23 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Insufficient Content

Additional info- the instructions are very vague and not informative. i had to refer to a youtube video to learn how to do the simulation. unlike DES, this is not helpful at all.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/procedure.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1724215924778.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-19 15:18
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 15:18 UTC
Labels: duplicate, IIITH
