### ISSUE TITLE
[BUG REPORT] Venturi Meter Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#425] opened 2024-07-15 17:32 UTC
### **Bug Reported on 15 July, 23:2 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Venturi Meter Experiment
**Type(s) of Issue -**
* Incorrect Content

Additional info- Gshsj

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/venturi-meter/simulation.html

**Comment by shraddha** [comment] 2024-11-28 14:11
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/426 Hence closing.

**Closed by shraddha** 2024-11-28 14:11 UTC
Labels: duplicate, IIITH
