### ISSUE TITLE
[BUG REPORT] Mouthpieces Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4279] opened 2024-11-19 16:35 UTC
### **Bug Reported on 19 November, 22:5 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Mouthpieces Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation not working

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/mouthpieces/simulation.html

**Comment by shraddha** [comment] 2024-11-28 14:30
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3277 Hence closing.

**Closed by shraddha** 2024-11-28 14:30 UTC
Labels: duplicate, IIITH
