### ISSUE TITLE
[BUG REPORT] Grain Size Distribution

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4079] opened 2024-11-12 09:43 UTC
### **Bug Reported on 12 November, 15:13 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Grain Size Distribution
**Type(s) of Issue -**

Additional info- Soil

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/grain-size-distribution/simulation.html

**Comment by shraddha** [comment] 2024-11-28 15:16
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2360 Hence closing.

**Closed by shraddha** 2024-11-28 15:16 UTC
Labels: duplicate, IIITH
