### ISSUE TITLE
[BUG REPORT] Recursion

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4443] opened 2024-11-28 05:28 UTC
### **Bug Reported on 28 November, 10:58 GMT +5:50 in** 
Lab - Computer programming
Experiment - Recursion
**Type(s) of Issue -**
* Incorrect Answer

Additional info- no answer of 3rd question in pretest matches correct answer  is 20 40 80 80 40 20

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-recursion/pretest.html

**Comment by shraddha** [comment] 2024-11-28 05:40
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4442 hence closing it.

**Closed by shraddha** 2024-11-28 05:40 UTC
Labels: duplicate, IIITH
