### ISSUE TITLE
[BUG REPORT] Bernoulli's Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#565] opened 2024-07-22 15:06 UTC
### **Bug Reported on 22 July, 20:36 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Bernoulli's Experiment
**Type(s) of Issue -**
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions

Additional info- Incorrect result 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/bernoullis/simulation.html
Email - sanadiasma58@gmail.com

**Comment by shraddha** [comment] 2024-11-27 13:24
This is the duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3735, and hence closing.

**Closed by shraddha** 2024-11-27 13:24 UTC
Labels: duplicate, IIITH
