### ISSUE TITLE
[BUG REPORT] Orifices Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3551] opened 2024-10-22 16:43 UTC
### **Bug Reported on 22 October, 22:13 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Orifices Experiment
**Type(s) of Issue -**
* Content Not Visible

Additional info- I can’t see the experiment 

UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/orifices/

**Comment by shraddha** [comment] 2024-11-28 05:52
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/289 Hence closing.

**Closed by shraddha** 2024-11-28 05:52 UTC
Labels: duplicate, IIITH
