### ISSUE TITLE
[BUG REPORT] Virtual Labs Pointers

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4101] opened 2024-11-13 05:49 UTC
### **Bug Reported on 12 November, 21:49 GMT -8:0 in** 
Lab - Computer programming
Experiment - Pointers
**Type(s) of Issue -**
* Page Not Loading
* Insufficient/Incorrect Instructions
* Incorrect Results/Observations
* Simulation Not Working
* Content Not Visible
* Incorrect Content

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/pointers/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1731476965780.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 04:23
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/306 hence closing it.

**Closed by shraddha** 2024-11-28 04:23 UTC
Labels: duplicate, IIITH
