### ISSUE TITLE
[BUG REPORT] Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4921] opened 2024-12-24 13:52 UTC
### **Bug Reported on 24 December, 19:22 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Not working 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/simulation.html

**Comment by shraddha** [comment] 2024-12-25 05:56
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/371 Hence closing.

**Closed by shraddha** 2024-12-25 05:56 UTC
Labels: duplicate, IIITH
