### ISSUE TITLE
[BUG REPORT] Virtual Labs Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4205] opened 2024-11-15 14:02 UTC
### **Bug Reported on 15 November, 19:16 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**

Additional info- coad is not executing

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1731679339605.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-19 13:54
Closing the bug as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237

**Closed by shraddha** 2024-11-19 13:54 UTC
Labels: duplicate, IIITH
