### ISSUE TITLE
[BUG REPORT] Structures

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#656] opened 2024-07-26 07:39 UTC
### **Bug Reported on 26 July, 13:9 GMT +5:50 in** 
Lab - Computer programming
Experiment - Structures
**Type(s) of Issue -**
* Page Not Loading

Additional info- .

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/structures/theory.html

**Comment by shraddha** [comment] 2024-11-29 12:01
Page seems to be loading properly now, hence marking as Not reproducible and closing it.

**Closed by shraddha** 2024-11-29 12:01 UTC
Labels: IIITH, Not Reproducible
