### ISSUE TITLE
[BUG REPORT] Virtual Labs Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3995] opened 2024-11-08 05:17 UTC
### **Bug Reported on 8 November, 10:46 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Simulation Not Working
* Content Not Visible
* Simulation Not Working

Additional info- solve the problem

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html
Email - harshit412050@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1731043018959.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-25 14:22
This seems to be duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237, hence closing it.

**Closed by shraddha** 2024-11-25 14:22 UTC
Labels: duplicate, IIITH
