### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#390] opened 2024-07-10 06:13 UTC
### **Bug Reported on 10 July, 11:42 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Page Not Loading

Additional info- UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/assignment.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1720591980702.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-21 11:12
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/409, hence closing it.

**Closed by shraddha** 2024-11-21 11:12 UTC
Labels: duplicate, IIITH
