### ISSUE TITLE
[BUG REPORT] Linked lists

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4441] opened 2024-11-28 05:22 UTC
### **Bug Reported on 28 November, 10:52 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Linked lists
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Hi

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/linked-list/singly-linked-list/sllpractice.html
Email - krishnavenkata675@gmail.com

**Comment by shraddha** [comment] 2024-11-28 05:42
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3512 hence closing it.

**Closed by shraddha** 2024-11-28 05:42 UTC
Labels: duplicate, IIITH
