### ISSUE TITLE
[BUG REPORT] Linked lists

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2595] opened 2024-10-01 08:36 UTC
### **Bug Reported on 1 October, 14:6 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Linked lists
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- We observe result step by step 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/linked-lists/doubly-linked-list/dllexercise.html

**Comment by shraddha** [comment] 2024-11-27 15:05
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4298, hence closing it.

**Closed by shraddha** 2024-11-27 15:05 UTC
Labels: duplicate, IIITH
