### ISSUE TITLE
[BUG REPORT] Classes and Objects

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2556] opened 2024-09-30 09:51 UTC
### **Bug Reported on 30 September, 15:21 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Classes and Objects
**Type(s) of Issue -**
* Simulation Not Working
* Content Not Visible

Additional info- Content not visible

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/classes-and-objects/simulation.html

**Comment by vlabiitk** [comment] 2024-12-20 12:34
Duplicate of #2555

**Closed by vlabiitk** 2024-12-20 12:34 UTC
Labels: duplicate, IITK
