### ISSUE TITLE
[BUG REPORT] Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4168] opened 2024-11-14 07:27 UTC
### **Bug Reported on 14 November, 12:57 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Page Not Loading

Additional info- Not loading 

UserAgent: Mozilla/5.0 (Linux; Android 14; SAMSUNG SM-E156B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/115.0.0.0 Mobile Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/
Email - sensayana2007@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1731569101028.png" alt="Issue image">

**Comment by vlab-iitr** [comment] 2024-12-09 06:17
Based on the attached experiment link - Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 06:17 UTC
Labels: duplicate, IITR
