### ISSUE TITLE
[BUG REPORT] Virtual Labs Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3417] opened 2024-10-18 09:24 UTC
### **Bug Reported on 18 October, 14:54 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Simulation Not Working

Additional info- the enter the start range isnt working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 09:52
Duplicate of #3305

**Closed by vlabiitk** 2024-12-24 09:52 UTC
Labels: duplicate, IITK
