### ISSUE TITLE
[BUG REPORT] Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2049] opened 2024-09-17 03:17 UTC
### **Bug Reported on 17 September, 8:47 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**

Additional info- Answes not submitted 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/simulation.html
Email - jungleeblaster@gmail.com

**Comment by shraddha** [comment] 2024-11-28 11:49
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1052 Hence closing it.

**Closed by shraddha** 2024-11-28 11:49 UTC
Labels: duplicate, IIITH
