### ISSUE TITLE
[BUG REPORT] Infix to Postfix

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4504] opened 2024-12-01 11:37 UTC
### **Bug Reported on 1 December, 17:7 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Infix to Postfix
**Type(s) of Issue -**

Additional info- output not coming

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/infix-postfix/code-assessment.html
Email - skroy.toto@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1733053029186.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-12-02 09:46
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4503 Hence closing.

**Closed by shraddha** 2024-12-02 09:46 UTC
Labels: duplicate, IIITH
