### ISSUE TITLE
[BUG REPORT] Virtual Labs Familiarization with the fluorescence Instrumentation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1972] opened 2024-09-12 14:10 UTC
### **Bug Reported on 12 September, 22:9 GMT +8:0 in** 
Lab - Molecular Fluorescence Spectroscopy
Experiment - Familiarization with the fluorescence Instrumentation
**Type(s) of Issue -**
* Simulation Not Working
* Content Not Visible

Additional info- It's just a white screen

UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Experiment Link - https://mfs-iiith.vlabs.ac.in/exp/fluorescence-instrumentation/simulation.html

**Comment by shraddha** [comment] 2024-11-28 11:32
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1666 Hence closing.

**Closed by shraddha** 2024-11-28 11:32 UTC
Labels: duplicate, IIITH
