### ISSUE TITLE
[BUG REPORT] Stacks Queues

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4498] opened 2024-12-01 06:47 UTC
### **Bug Reported on 1 December, 12:17 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Stacks Queues
**Type(s) of Issue -**

Additional info- i am not able to submit the code and the output

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/stacks-queues/code-assessment.html
Email - sara2005nya@gmail.com

**Comment by shraddha** [comment] 2024-12-02 10:57
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3460 hence closing.

**Closed by shraddha** 2024-12-02 10:57 UTC
Labels: duplicate, IIITH
