### ISSUE TITLE
[BUG REPORT] Virtual Labs Digital Signatures

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2439] opened 2024-09-26 06:30 UTC
### **Bug Reported on 25 September, 22:30 GMT -8:0 in** 
Lab - Cryptography
Experiment - Digital Signatures
**Type(s) of Issue -**
* Page Not Loading

Additional info- Very bad expirence 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/digital-signatures/simulation.html
Email - yashp@gmaili.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1727332241015.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 14:56
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/248 Hence closing.

**Closed by shraddha** 2024-11-28 14:56 UTC
Labels: duplicate, IIITH
