### ISSUE TITLE
[BUG REPORT] Breaking the Mono-alphabetic Substitution Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2134] opened 2024-09-20 05:18 UTC
### **Bug Reported on 20 September, 10:50 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Mono-alphabetic Substitution Cipher
**Type(s) of Issue -**
* Incorrect Content

Additional info- WRONG SPELLING OF SIMILARITIES IN STEP 4

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/substitution-cipher/procedure.html
Email - tulsyanigarv@gmail.com

**Comment by shraddha** [comment] 2024-11-28 07:31
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/411 Hence closing.

**Closed by shraddha** 2024-11-28 07:31 UTC
Labels: duplicate, IIITH
