### ISSUE TITLE
[BUG REPORT] Virtual Labs Bernoulli's Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4293] opened 2024-11-20 09:18 UTC
### **Bug Reported on 20 November, 14:48 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Bernoulli's Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- not working properly

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/bernoullis/simulation.html

**Comment by shraddha** [comment] 2024-11-27 13:24
This is the duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3735, and hence closing.

**Closed by shraddha** 2024-11-27 13:24 UTC
Labels: duplicate, IIITH
