### ISSUE TITLE
[BUG REPORT] Torsion Test Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1741] opened 2024-09-04 12:46 UTC
### **Bug Reported on 4 September, 15:46 GMT +3:0 in** 
Lab - Basic Engineering Mechanics and Strength Of Materials
Experiment - Torsion Test Experiment
**Type(s) of Issue -**
* Insufficient Content

Additional info- experiments 

UserAgent: Mozilla/5.0 (Linux; Android 11; itel A512W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.98 Mobile Safari/537.36
Experiment Link - https://eerc01-iiith.vlabs.ac.in/exp/torsion-test-experiment/
Email - derrickproug35@gmail.com

**Comment by shraddha** [comment] 2024-11-28 14:13
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1031 Hence closing.

**Closed by shraddha** 2024-11-28 14:13 UTC
Labels: duplicate, IIITH
