### ISSUE TITLE
[BUG REPORT] Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4367] opened 2024-11-24 13:18 UTC
### **Bug Reported on 24 November, 18:48 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Simulation Not Working
* Page Not Loading

Additional info- Page not loading

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html
Email - mukeshravi0801@gmail.com

**Comment by vlab-iitr** [comment] 2024-12-09 06:20
Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 06:20 UTC
Labels: duplicate, IITR
