### ISSUE TITLE
[BUG REPORT] Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1736] opened 2024-09-04 10:08 UTC
### **Bug Reported on 4 September, 15:38 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Incorrect Results/Observations
* Simulation Not Working

Additional info- Incorrect answer 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 06:27
Duplicate of #1735

**Closed by vlabiitk** 2024-12-24 06:27 UTC
Labels: duplicate, IITK
