### ISSUE TITLE
[BUG REPORT] Virtual Labs Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3304] opened 2024-10-17 04:53 UTC
### **Bug Reported on 17 October, 10:23 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Simulation Not Working
* Simulation Not Working

Additional info- the simulator for prime numbers is not working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html
Email - vinayak.pai@somaiya.edu

**Comment by vlabiitk** [comment] 2024-12-24 06:24
Duplicate of #3305

**Closed by vlabiitk** 2024-12-24 06:24 UTC
Labels: duplicate, IITK
