### ISSUE TITLE
[BUG REPORT] Compaction Test

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3652] opened 2024-10-25 05:08 UTC
### **Bug Reported on 25 October, 10:37 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Compaction Test
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation is not working as well as no showing 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/compaction-test/simulation.html
Email - mousamm511@gmail.com

**Comment by shraddha** [comment] 2024-11-29 11:52
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2034 Hence closing it.

**Closed by shraddha** 2024-11-29 11:52 UTC
Labels: duplicate, IIITH
