### ISSUE TITLE
[BUG REPORT] Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3639] opened 2024-10-24 17:55 UTC
### **Bug Reported on 24 October, 23:25 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Page Not Loading

Additional info- It is like when giving the output after the performing the operation it is showing giving the confirmation of whether the final ciphertext is correct or Incorrect

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1729792539012.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-19 15:24
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 15:24 UTC
Labels: duplicate, IIITH
