### ISSUE TITLE
[BUG REPORT] Virtual Labs Finding Viscosity of Liquid by Rotating Cylinder Method

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2090] opened 2024-09-19 05:52 UTC
### **Bug Reported on 19 September, 11:22 GMT +5:50 in** 
Lab - Basics of Physics
Experiment - Finding Viscosity of Liquid by Rotating Cylinder Method
**Type(s) of Issue -**
* Simulation Not Working

Additional info- dont show the distance and stop watch

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://bop-iitk.vlabs.ac.in/exp/liquid-viscosity/simulation.html

**Comment by vlabiitk** [comment] 2024-12-26 11:49
Duplicate of #4011

**Closed by vlabiitk** 2024-12-26 11:49 UTC
Labels: duplicate, IITK
