### ISSUE TITLE
[BUG REPORT] Finding Viscosity of Liquid by Rotating Cylinder Method

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4627] opened 2024-12-08 13:22 UTC
### **Bug Reported on 8 December, 21:22 GMT +8:0 in** 
Lab - Basics of Physics
Experiment - Finding Viscosity of Liquid by Rotating Cylinder Method
**Type(s) of Issue -**
* Simulation Not Working

Additional info- I cannot drag the ball to the jar

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://bop-iitk.vlabs.ac.in/exp/liquid-viscosity/simulation.html

**Comment by vlabiitk** [comment] 2024-12-26 11:39
Duplicate of #4709

**Closed by vlabiitk** 2024-12-26 11:39 UTC
Labels: duplicate, IITK
