### ISSUE TITLE
[BUG REPORT] Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1299] opened 2024-08-22 06:31 UTC
### **Bug Reported on 22 August, 12:1 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Incorrect Content

Additional info- area of semicircle can not be calculated by the given function 

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html

**Comment by shraddha** [comment] 2024-11-25 14:24
This seems to be duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237, hence closing it.

**Closed by shraddha** 2024-11-25 14:24 UTC
Labels: duplicate, IIITH
