### ISSUE TITLE
[BUG REPORT] Infix to Postfix

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4481] opened 2024-11-29 14:06 UTC
### **Bug Reported on 29 November, 19:36 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Infix to Postfix
**Type(s) of Issue -**
* Incorrect Content
* Page Not Loading
* Insufficient Content
* Content Not Visible

Additional info- .

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/infix-postfix/index.html

**Comment by shraddha** [comment] 2024-12-02 09:44
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3614 hence closing.

**Closed by shraddha** 2024-12-02 09:44 UTC
Labels: duplicate, IIITH
