### ISSUE TITLE
[BUG REPORT] Functions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4518] opened 2024-12-02 06:06 UTC
### **Bug Reported on 2 December, 11:36 GMT +5:50 in** 
Lab - Computer programming
Experiment - Functions
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Here in the responsiveness of this stimulating in mobile view it shows menu in left bottom and the it also not proper responsive

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/functions/simulation.html
Email - suyashvats05@gmail.com

**Comment by shraddha** [comment] 2024-12-02 10:54
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4237 hence closing.

**Closed by shraddha** 2024-12-02 10:54 UTC
Labels: duplicate, IIITH
