### ISSUE TITLE
[BUG REPORT] Determination of Hardness in water

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#624] opened 2024-07-25 05:53 UTC
### **Bug Reported on 25 July, 11:23 GMT +5:50 in** 
Lab - Environmental Engineering 1
Experiment - Determination of Hardness in water
**Type(s) of Issue -**
* Content Not Visible

Additional info- Thank you 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
Experiment Link - https://ee1-nitk.vlabs.ac.in/exp/determination-of-hardness/simulation.html
Email - parveengudagi2@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/COEP1721886670187.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment] 2024-12-03 09:57
Screenshot shared is not of "Determination of Hardness in water" experiment. So the issue is not relevant to the experiment. Closing the issue with the label 'Inappropriate'.

**Closed by SOLVE-NITK** 2024-12-03 09:57 UTC
Labels: NITK, Inappropriate
