### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Mono-alphabetic Substitution Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1054] opened 2024-08-10 17:53 UTC
### **Bug Reported on 10 August, 23:23 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Mono-alphabetic Substitution Cipher
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- Wrong results

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/substitution-cipher/simulation.html
Email - mrunalt22it@student.mes.ac.in

**Comment by shraddha** [comment] 2024-11-28 07:30
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/411 Hence closing.

**Closed by shraddha** 2024-11-28 07:30 UTC
Labels: duplicate, IIITH
