### ISSUE TITLE
[BUG REPORT] Virtual Labs Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#310] opened 2024-06-19 15:44 UTC
### **Bug Reported on 19 June, 21:14 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Page Not Loading

Additional info- page is not loading!

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html

**Comment by vlab-iitr** [comment] 2024-12-09 05:11
Closing it, as it is a duplicate of #152

**Closed** 2024-12-09 05:15 UTC
Labels: duplicate, IITR
