### ISSUE TITLE
[BUG REPORT] Virtual Labs Fatigue Test Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#296] opened 2024-06-03 04:20 UTC
### **Bug Reported on 3 June, 9:50 GMT +5:50 in** 
Lab - Basic Engineering Mechanics and Strength Of Materials
Experiment - Fatigue Test Experiment
**Type(s) of Issue -**
* Simulation Not Working
* Insufficient/Incorrect Instructions

Additional info- the input parameters part is not accepting any command.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://eerc01-iiith.vlabs.ac.in/exp/fatigue-test-experiment/simulation.html
Email - 2021pcemeibrahim006@poornima.org

**Comment by shraddha** [comment] 2024-11-29 10:58
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1900 Hence closing.

**Closed by shraddha** 2024-11-29 10:58 UTC
Labels: duplicate, IIITH
