### ISSUE TITLE
[BUG REPORT] Virtual Labs Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3283] opened 2024-10-16 09:26 UTC
### **Bug Reported on 16 October, 14:56 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**

Additional info- i dont like how the whole values saved once erase after completing one task

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/simulation.html

**Comment by shraddha** [comment] 2024-11-28 11:51
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1052 Hence closing it.

**Closed by shraddha** 2024-11-28 11:51 UTC
Labels: duplicate, IIITH
