### ISSUE TITLE
[BUG REPORT]  Familiarization of ICs

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1226] opened 2024-08-20 15:48 UTC
### **Bug Reported on 20 August, 21:18 GMT +5:50 in** 
Lab - Analog and Digital Electronics I
Experiment -  Familiarization of ICs
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Connections are not connecting

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://ade-iitr.vlabs.ac.in/exp/familiarization-of-ics/simulation.html

**Comment by vlab-iitr** [comment] 2024-11-28 09:54
Closing it, as it is a duplicate of #1225

**Closed by vlab-iitr** 2024-11-28 09:54 UTC
Labels: duplicate, IITR
