### ISSUE TITLE
[BUG REPORT] Virtual Labs Path algorithms: Dijkstra's shortest path

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4794] opened 2024-12-16 04:06 UTC
### **Bug Reported on 16 December, 9:36 GMT +5:50 in** 
Lab - Data Structures - 2
Experiment - Path algorithms: Dijkstra's shortest path
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions

Additional info- The simulation is not working in the exercise and practice section. 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://ds2-iiith.vlabs.ac.in/exp/dijkstra-algorithm/dijkstras-algorithm/DijkstrasExercise.html

**Comment by shraddha** [comment] 2024-12-16 11:03
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2928 Hence closing.

**Closed by shraddha** 2024-12-16 11:03 UTC
Labels: duplicate, IIITH
