### ISSUE TITLE
[BUG REPORT] Virtual Labs Schematic Design Of Transistor Level Inverter

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1780] opened 2024-09-06 05:25 UTC
### **Bug Reported on 6 September, 10:54 GMT +5:50 in** 
Lab - VLSI
Experiment - Schematic Design Of Transistor Level Inverter
**Type(s) of Issue -**
* Simulation Not Working
* Insufficient/Incorrect Instructions

Additional info- Simulator not loading

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse14-iiith.vlabs.ac.in/exp/transistor-level-inverter/simulation.html
Email - suryadeo.bit@gmail.com

**Comment by shraddha** [comment] 2024-11-28 14:08
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/298 Hence closing.

**Closed by shraddha** 2024-11-28 14:08 UTC
Labels: duplicate, IIITH
