### ISSUE TITLE
[BUG REPORT] Arithmetic Operations

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1171] opened 2024-08-17 03:54 UTC
### **Bug Reported on 17 August, 9:23 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Arithmetic Operations
**Type(s) of Issue -**
* Incorrect Results/Observations
* Page Not Loading
* Insufficient/Incorrect Instructions

Additional info- Fufjdjr

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/arithmetic-operations/simulation.html

**Comment by vlabiitk** [comment] 2024-12-24 05:11
Duplicate of #836

**Closed by vlabiitk** 2024-12-24 05:11 UTC
Labels: duplicate, IITK
