### ISSUE TITLE
[BUG REPORT] Virtual Labs Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4085] opened 2024-11-12 13:04 UTC
### **Bug Reported on 12 November, 18:34 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Simulation Not Working

Additional info- your site doesnt show the correct or wrong output. it is not providing result

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html
Email - saritabassi01@gmail.com

**Comment by shraddha** [comment] 2024-11-19 13:57
Closing the bug as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4084

**Closed by shraddha** 2024-11-19 13:57 UTC
Labels: duplicate, IIITH
