### ISSUE TITLE
[BUG REPORT] Characteristic parameters of Op-Amp

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1042] opened 2024-08-09 11:52 UTC
### **Bug Reported on 9 August, 17:22 GMT +5:50 in** 
Lab - Analog and Digital Electronics II
Experiment - Characteristic parameters of Op-Amp
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Components was not connected on mobile and smart board

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://ade2-iitr.vlabs.ac.in/exp/characteristic-parameters/simulation.html

**Comment by vlab-iitr** [comment] 2024-11-29 05:12
Closing it, as it is a duplicate of #1041

**Closed by vlab-iitr** 2024-11-29 05:12 UTC
Labels: duplicate, IITR
