### ISSUE TITLE
[BUG REPORT] Symmetric Key Encryption Standards (AES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2394] opened 2024-09-25 09:24 UTC
### **Bug Reported on 25 September, 14:54 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (AES)
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Check Answer Button is not responding 

UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/aes/simulation.html
Email - rishi010804@gmail.com

**Comment by shraddha** [comment] 2024-11-19 15:22
Closing it, as it is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/220

**Closed by shraddha** 2024-11-19 15:22 UTC
Labels: duplicate, IIITH
