### ISSUE TITLE
[BUG REPORT] Virtual Labs Loops

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1598] opened 2024-08-31 13:46 UTC
### **Bug Reported on 31 August, 19:16 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Loops
**Type(s) of Issue -**
* Simulation Not Working

Additional info- simulation not working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/loops/simulation.html
Email - raikeshav143@gmail.com

**Comment by vlabiitk** [comment] 2024-12-24 06:30
Duplicate of #1709

**Closed by vlabiitk** 2024-12-24 06:30 UTC
Labels: duplicate, IITK
