### ISSUE TITLE
[BUG REPORT] Virtual Labs Free Vibration of S.D.O.F System

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4473] opened 2024-11-29 09:28 UTC
### **Bug Reported on 29 November, 14:58 GMT +5:50 in** 
Lab - Structural Dynamics
Experiment - Free Vibration of S.D.O.F System
**Type(s) of Issue -**
* Insufficient/Incorrect Instructions
* Incorrect Results/Observations
* Simulation Not Working

Additional info- Graphs are not generated

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://sd-iiith.vlabs.ac.in/exp/free-vibration/simulation.html
Email - manikseb@gmail.com

**Comment by shraddha** [comment] 2024-11-29 09:39
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2929 Hence closing.

**Closed by shraddha** 2024-11-29 09:39 UTC
Labels: duplicate, IIITH
