### ISSUE TITLE
[BUG REPORT] Basic Control Flow

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4905] opened 2024-12-23 16:47 UTC
### **Bug Reported on 23 December, 9:46 GMT +5:50 in** 
Lab - Computer programming
Experiment - Basic Control Flow
**Type(s) of Issue -**
* Incorrect Answer
* Incorrect Options

Additional info- Some answers are wrong. I have solved in virtual lab.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/basic-control-flow/posttest.html
Email - kalamberupesh342gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1734972443595.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-12-25 05:50
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/233 Hence closing.

**Closed by shraddha** 2024-12-25 05:50 UTC
Labels: duplicate, IIITH
