### ISSUE TITLE
[BUG REPORT] Pointers

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1779] opened 2024-09-06 03:47 UTC
### **Bug Reported on 6 September, 9:17 GMT +5:50 in** 
Lab - Computer programming
Experiment - Pointers
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation not working

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/pointers/simulation.html

**Comment by shraddha** [comment] 2024-11-28 04:21
This bug is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/306 hence closing it.

**Closed by shraddha** 2024-11-28 04:21 UTC
Labels: duplicate, IIITH
