### ISSUE TITLE
[BUG REPORT] Virtual Labs Strings

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#788] opened 2024-07-31 05:12 UTC
### **Bug Reported on 31 July, 10:42 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Strings
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- input for n should be in integer 

UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0
Experiment Link - https://python-iitk.vlabs.ac.in/exp/strings/simulation.html
Email - laiba.ali.020205@gmail.com

**Comment by vlabiitk** [comment] 2024-12-20 12:19
This issue is duplicate of #3489.

**Closed by vlabiitk** 2024-12-20 12:19 UTC
Labels: duplicate, IITK
