### ISSUE TITLE
[BUG REPORT] Preparation of Sols

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4041] opened 2024-11-10 14:29 UTC
### **Bug Reported on 10 November, 19:59 GMT +5:50 in** 
Lab - Colloid and Surface Chemistry Virtual Lab
Experiment - Preparation of Sols
**Type(s) of Issue -**
* Insufficient/Incorrect Instructions
* Content Not Visible

Additional info- Contents not visible 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36
Experiment Link - https://csc-iiith.vlabs.ac.in/exp/preparation-of-sols/simulation.html

**Comment by shraddha** [comment] 2024-11-29 11:09
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2109 Hence closing.

**Closed by shraddha** 2024-11-29 11:09 UTC
Labels: duplicate, IIITH
