### ISSUE TITLE
[BUG REPORT] Virtual Labs Determination of Dissolved Oxygen in water 

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3583] opened 2024-10-23 10:00 UTC
### **Bug Reported on 23 October, 15:30 GMT +5:50 in** 
Lab - Environmental Engineering 2
Experiment - Determination of Dissolved Oxygen in water 
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Content Not Visible
* Incorrect Content
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Incorrect Content
* Content Not Visible

Additional info- slowwwwwww

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://ee2-nitk.vlabs.ac.in/exp/oxygen-in-water/simulation.html

**Comment by SOLVE-NITK** [comment] 2024-12-03 11:17
The issue is not relevant to the experiment. Closing the issue with the label 'Inappropriate'. Unable to reproduce. Additional details required to analyze further.

**Closed by SOLVE-NITK** 2024-12-03 11:17 UTC
Labels: NITK, Inappropriate, Not Reproducible
