### ISSUE TITLE
[BUG REPORT] Izod Impact Test

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4468] opened 2024-11-29 05:59 UTC
### **Bug Reported on 29 November, 11:29 GMT +5:50 in** 
Lab - Virtual Strength of Materials Lab
Experiment - Izod Impact Test
**Type(s) of Issue -**
* Page Not Loading
* Insufficient Content

Additional info- All content and pages are not opening.

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://sm-nitk.vlabs.ac.in/exp/izod-impact-test/

**Comment by SOLVE-NITK** [comment] 2024-12-05 11:30
Page is not loading. The issue is not relevant to the experiment. Closing the issue with the label 'Inappropriate'.

**Comment by shraddha** [comment] 2024-12-05 14:11
Please review the labeling by referring to the section 'Categorize the bug' from [Bug Management Process](https://vlead.vlabs.ac.in/development/#bug-processing-guide). This bug seems to fall into either of these categories - invalid or Not Reproducible.  Hence removing the inappropriate label and reopening the bug for reassignment of right label.

**Comment by SOLVE-NITK** [comment] 2024-12-17 07:02
@shraddha Label is changed to invalid

**Closed by SOLVE-NITK** 2024-12-17 07:02 UTC
Labels: invalid, NITK
