### ISSUE TITLE
[BUG REPORT] Compaction Test

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2276] opened 2024-09-23 09:18 UTC
### **Bug Reported on 23 September, 14:48 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Compaction Test
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Solve quickly 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/compaction-test/simulation.html

**Comment by shraddha** [comment] 2024-11-29 11:53
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2034 Hence closing it.

**Closed by shraddha** 2024-11-29 11:53 UTC
Labels: duplicate, IIITH
