### ISSUE TITLE
[BUG REPORT] Virtual Labs Speed Control of DC motor by field resistance control

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1198] opened 2024-08-19 16:08 UTC
### **Bug Reported on 19 August, 21:38 GMT +5:50 in** 
Lab - Electrical Machines (Simulation)
Experiment - Speed Control of DC motor by field resistance control
**Type(s) of Issue -**
* Simulation Not Working

Additional info- stimulation is not showing 

UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://ems-iitr.vlabs.ac.in/exp/dcmotor-field-resistance-control/simulation.html

**Comment by vlab-iitr** [comment] 2024-12-09 05:28
Closing it, as it is a duplicate of #152

**Closed by vlab-iitr** 2024-12-09 05:28 UTC
Labels: duplicate, IITR
