### ISSUE TITLE
[BUG REPORT] Bubble Sort

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4886] opened 2024-12-21 10:04 UTC
### **Bug Reported on 21 December, 15:34 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Bubble Sort
**Type(s) of Issue -**
* Insufficient Content

Additional info- no

UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/131.0.6778.154 Mobile/15E148 Safari/604.1
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/bubble-sort/index.html

**Comment by shraddha** [comment] 2024-12-25 05:48
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4739 Hence closing.

**Closed by shraddha** 2024-12-25 05:48 UTC
Labels: duplicate, IIITH
