### ISSUE TITLE
[BUG REPORT] Virtual Labs Digital Signatures

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4745] opened 2024-12-12 12:47 UTC
### **Bug Reported on 12 December, 18:17 GMT +5:50 in** 
Lab - Cryptography
Experiment - Digital Signatures
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Error while clicking Apply RSA

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/digital-signatures/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1734007673049.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-12-14 11:17
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/248 Hence closing.

**Closed by shraddha** 2024-12-14 11:17 UTC
Labels: duplicate, IIITH
