### ISSUE TITLE
[BUG REPORT] Virtual Labs Depth First Search

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2390] opened 2024-09-25 08:32 UTC
### **Bug Reported on 25 September, 14:2 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Depth First Search
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations

Additional info- java script error

UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/depth-first-search/dfs/dfs-exercise.html

**Comment by shraddha** [comment] 2024-11-27 15:21
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/3582, hence closing it.

**Closed by shraddha** 2024-11-27 15:21 UTC
Labels: duplicate, IIITH
