### ISSUE TITLE
[BUG REPORT] Classes and Objects

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#650] opened 2024-07-26 06:27 UTC
### **Bug Reported on 26 July, 12:5 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Classes and Objects
**Type(s) of Issue -**
* Page Not Loading
* Insufficient Content

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/classes-and-objects/
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITK1721975235137.png" alt="Issue image">

**Comment by vlabiitk** [comment] 2024-12-20 12:35
Duplicate of #3605

**Closed by vlabiitk** 2024-12-20 12:35 UTC
Labels: duplicate, IITK
