### ISSUE TITLE
[BUG REPORT] Constructors and Inheritance

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3015] opened 2024-10-08 08:44 UTC
### **Bug Reported on 8 October, 14:14 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Constructors and Inheritance
**Type(s) of Issue -**
* Incorrect Content

Additional info- Test is not submitting and it does't show anything when the test is completed.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/constructors-and-inheritance/posttest.html

**Comment by vlabiitk** [comment] 2024-12-20 12:41
Duplicate of #1318

**Closed by vlabiitk** 2024-12-20 12:41 UTC
Labels: duplicate, IITK
