### ISSUE TITLE
[BUG REPORT] Virtual Labs Grain Size Distribution

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2468] opened 2024-09-26 21:18 UTC
### **Bug Reported on 26 September, 17:18 GMT -4:0 in** 
Lab - Soil Mechanics
Experiment - Grain Size Distribution
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/grain-size-distribution/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1727385502805.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-28 15:16
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/2360 Hence closing.

**Closed by shraddha** 2024-11-28 15:16 UTC
Labels: duplicate, IIITH
