### ISSUE TITLE
[BUG REPORT] Specific Gravity

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4082] opened 2024-11-12 09:51 UTC
### **Bug Reported on 12 November, 15:20 GMT +5:50 in** 
Lab - Soil Mechanics
Experiment - Specific Gravity
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Repeat simulation is bad

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36
Experiment Link - https://smfe-iiith.vlabs.ac.in/exp/specific-gravity/simulation.html

**Comment by shraddha** [comment] 2024-11-28 14:19
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/4327 Hence closing.

**Closed by shraddha** 2024-11-28 14:19 UTC
Labels: duplicate, IIITH
