### ISSUE TITLE
[BUG REPORT] Virtual Labs  Familiarization of ICs

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1988] opened 2024-09-13 05:54 UTC
### **Bug Reported on 13 September, 11:24 GMT +5:50 in** 
Lab - Analog and Digital Electronics I
Experiment -  Familiarization of ICs
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations
* Insufficient/Incorrect Instructions
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- mue hehe

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://ade-iitr.vlabs.ac.in/exp/familiarization-of-ics/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1726206250623.png" alt="Issue image">

**Comment by vlab-iitr** [comment] 2024-11-28 09:50
Closing it, as it is a duplicate of #1987

**Closed by vlab-iitr** 2024-11-28 09:50 UTC
Labels: duplicate, IITR
