### ISSUE TITLE
[BUG REPORT] Quick Sort

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4357] opened 2024-11-24 04:03 UTC
### **Bug Reported on 24 November, 9:33 GMT +5:50 in** 
Lab - Data Structures - 1
Experiment - Quick Sort
**Type(s) of Issue -**
* Page Not Loading

Additional info- No out put

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://ds1-iiith.vlabs.ac.in/exp/quick-sort/code-assessment.html

**Comment by shraddha** [comment] 2024-11-26 16:12
Page is loading properly. The issue is not reproducing. Hence closing the issue.

**Closed by shraddha** 2024-11-26 16:12 UTC
Labels: IIITH, Not Reproducible
