### ISSUE TITLE
[BUG REPORT] Virtual Labs Breaking the Shift Cipher

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#408] opened 2024-07-15 08:49 UTC
### **Bug Reported on 15 July, 14:19 GMT +5:50 in** 
Lab - Cryptography
Experiment - Breaking the Shift Cipher
**Type(s) of Issue -**
* Simulation Not Working

Additional info- use function for shift in assignment page

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 OPR/111.0.0.0
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/shift-cipher/assignment.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1721033335008.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-21 11:14
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/409 hence closing it.

**Closed by shraddha** 2024-11-21 11:14 UTC
Labels: duplicate, IIITH
