### ISSUE TITLE
[BUG REPORT] Virtual Labs Symmetric Key Encryption Standards (DES)

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#297] opened 2024-06-04 09:13 UTC
### **Bug Reported on 4 June, 14:43 GMT +5:50 in** 
Lab - Cryptography
Experiment - Symmetric Key Encryption Standards (DES)
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Experiment Link - https://cse29-iiith.vlabs.ac.in/exp/des/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1717492414766.png" alt="Issue image">

**Comment by shraddha** [comment] 2024-11-21 12:23
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/228 Hence closing it.

**Closed by shraddha** 2024-11-21 12:23 UTC
Labels: duplicate, IIITH
