### ISSUE TITLE
[BUG REPORT] Arrays

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3328] opened 2024-10-17 06:17 UTC
### **Bug Reported on 17 October, 11:47 GMT +5:50 in** 
Lab - Computer programming
Experiment - Arrays
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Incorrect Content
* Content Not Visible
* Insufficient Content
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- Array program

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/arrays/

**Comment by shraddha** [comment] 2024-11-27 15:42
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1469, hence closing it.

**Closed by shraddha** 2024-11-27 15:42 UTC
Labels: duplicate, IIITH
