### ISSUE TITLE
[BUG REPORT] Expression Evaluation

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1756] opened 2024-09-05 11:00 UTC
### **Bug Reported on 5 September, 16:30 GMT +5:50 in** 
Lab - Computer programming
Experiment - Expression Evaluation
**Type(s) of Issue -**
* Incorrect Content

Additional info- 1 ) Here - have higher precedence than other operators. Why minus has higher precedence? 
Should it not be 2+5−10 is 7-10 is -3 ?

UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://cse02-iiith.vlabs.ac.in/exp/cp-expression-evaluation/simulation.html

**Comment by shraddha** [comment] 2024-11-28 11:48
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1052 Hence closing it.

**Closed by shraddha** 2024-11-28 11:48 UTC
Labels: duplicate, IIITH
